lang: es
quarto-required: ">= 1.4.0"

project:
  type: book
book:
  title: "Procesamiento de Lenguaje Natural"
  author: 
    - name: "Eric S. Téllez"
      url: https://sadit.github.io
      affiliation: INFOTEC Centro de Investigación e Innovación en Tecnologías de la Información y Comunicación    
    - name: "Mario Graff"
      url: https://mgraffg.github.io
      affiliation: INFOTEC Centro de Investigación e Innovación en Tecnologías de la Información y Comunicación
  chapters:
    - index.qmd
    - capitulos/01Introduccion.qmd
    - capitulos/02ManejandoTexto.qmd
    - capitulos/03ModeladoLenguaje.qmd
    - capitulos/04FundamentosCT.qmd
    - capitulos/05RepresentacionTexto.qmd
    - capitulos/06ClasificacionTexto.qmd
    - capitulos/07TareasClasificacion.qmd
    - capitulos/08BasesConocimiento.qmd
    - capitulos/09Visualizacion.qmd
    - capitulos/10Conclusiones.qmd
    - capitulos/11Referencias.qmd
  site-url: https://ingeotec.github.io/PLN
  repo-url: https://github.com/INGEOTEC/PLN
  downloads: pdf
  page-footer:
    right: |
      [![](https://i.creativecommons.org/l/by-sa/4.0/80x15.png)](http://creativecommons.org/licenses/by-sa/4.0/) <br/> Esta obra está bajo una [Licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional](http://creativecommons.org/licenses/by-sa/4.0/)             

bibliography: references.bib
title-block-banner: false

format:
  html:
    theme: cosmo
    code-tools: true
    echo: true
  pdf:
    documentclass: scrreprt
    echo: false

execute:
  freeze: auto