<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Representación de Texto – Procesamiento de Lenguaje Natural</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../capitulos/06ClasificacionTexto.html" rel="next">
<link href="../capitulos/04FundamentosCT.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-190b55869f1674f3654eb60e4236bfc9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/05RepresentacionTexto.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Representación de Texto</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Procesamiento de Lenguaje Natural</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/INGEOTEC/PLN" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/01Introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/02ManejandoTexto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Manejando Texto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/03ModeladoLenguaje.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelo de gramas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/04FundamentosCT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Fundamentos de Clasificación de Texto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/05RepresentacionTexto.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Representación de Texto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/06ClasificacionTexto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Clasificación de Texto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/07TareasClasificacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tareas de Clasificación de Texto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/08BasesConocimiento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Bases de Conocimiento</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/09Visualizacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Visualización</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/10Conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Conclusiones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/11Referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#paquetes-usados" id="toc-paquetes-usados" class="nav-link active" data-scroll-target="#paquetes-usados">Paquetes usados</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción"><span class="header-section-number">5.1</span> Introducción</a></li>
  <li><a href="#bolsa-de-palabras-dispersa" id="toc-bolsa-de-palabras-dispersa" class="nav-link" data-scroll-target="#bolsa-de-palabras-dispersa"><span class="header-section-number">5.2</span> Bolsa de Palabras Dispersa</a>
  <ul class="collapse">
  <li><a href="#pesado-de-términos" id="toc-pesado-de-términos" class="nav-link" data-scroll-target="#pesado-de-términos"><span class="header-section-number">5.2.1</span> Pesado de Términos</a></li>
  <li><a href="#sec-bolsa-dispersa-ejemplos" id="toc-sec-bolsa-dispersa-ejemplos" class="nav-link" data-scroll-target="#sec-bolsa-dispersa-ejemplos"><span class="header-section-number">5.2.2</span> Ejemplos</a></li>
  </ul></li>
  <li><a href="#bolsa-de-palabras-densa" id="toc-bolsa-de-palabras-densa" class="nav-link" data-scroll-target="#bolsa-de-palabras-densa"><span class="header-section-number">5.3</span> Bolsa de Palabras Densa</a>
  <ul class="collapse">
  <li><a href="#ejemplos" id="toc-ejemplos" class="nav-link" data-scroll-target="#ejemplos"><span class="header-section-number">5.3.1</span> Ejemplos</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Representación de Texto</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar todo el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Ocultar todo el código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver el código fuente</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>El <strong>objetivo</strong> de la unidad es analizar diferentes representaciones de texto basadas en vectores.</p>
<section id="paquetes-usados" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="paquetes-usados">Paquetes usados</h2>
<div id="832bbf60" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> EvoMSA <span class="im">import</span> BoW,<span class="op">\</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                   DenseBoW</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> microtc.utils <span class="im">import</span> tweet_iterator</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> wordcloud <span class="im">import</span> WordCloud                            </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pylab <span class="im">as</span> plt</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="introducción" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">5.1</span> Introducción</h2>
<p>En el <a href="04FundamentosCT.html" class="quarto-xref"><span>Capítulo 4</span></a> se describió un clasificador de texto que está basado en el modelo de lenguaje de gramas. Uno se podría imaginar que este clasificador representa de alguna manera al texto, es decir, que exite una estructura matemática donde los textos están representados. En este caso particular se observará que los textos están representados en un espacio vectorial. En los siguientes fragmentos de código se realizará una implementación equivalente que ayuda a visualizar esta representación.</p>
<p>Lo primer que se realiza es cargar el conjunto de datos que ha sido utilizado en el <a href="04FundamentosCT.html" class="quarto-xref"><span>Capítulo 4</span></a> y se crea un modelo de lenguaje (i.e., <code>ModeloNGram</code>) de unigramas y sin <span class="math inline">\(k\)</span>-suavizado.</p>
<div id="7115fc4b" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> load_dataset(lang<span class="op">=</span><span class="st">'es'</span>, dataset<span class="op">=</span><span class="st">'dev'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="op">=</span> ModeloNGram(N<span class="op">=</span><span class="dv">1</span>, k_suavizado<span class="op">=</span><span class="dv">0</span>).fit(dataset)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Los parametros se encuentran en las atributos <code>modelo.frase</code> y <code>modelo.hist</code>, en el caso de <code>modelo.hist</code> este tiene un valor de 3033366. Se observa que <code>modelo.frase</code> es un diccionario donde el índice es el identificador del segmento y el valor corresponde a la frecuencia. Por otro lado, el método <code>modelo._log_prob</code> (ver <a href="03ModeladoLenguaje.html#lst-modelo-n-gram" class="quarto-xref">Listado&nbsp;<span>3.5</span></a>) utiliza la información de <code>modelo.frase</code> y <code>modelo.hist</code> para calcular el logaritmo de la probabilidad. En las siguientes instrucciones se representa la información de <code>modelo.frase</code> y <code>modelo.hist</code> en un vector. Lo primero es guarda en la variable <code>den</code> el logaritmo de <code>modelo.hist</code>, después se utiliza la variable <code>idx</code> para dar un orden al vocabulario, es decir, el primer elemento de <code>idx</code> corresponderá a la primera palabra del vocabulario y así sucesivamente. Utilizando <code>idx</code> se itera por todo el vocabulario y se guarda el logaritmo de la probabilidad para cada segmento en el arreglo <code>pesos</code>.</p>
<div id="997a9e94" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>den <span class="op">=</span> np.log(modelo.hist)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> <span class="bu">sorted</span>(modelo.frase.keys())</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>pesos <span class="op">=</span> np.array(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    [np.log(modelo.frase[k]) <span class="op">-</span> den</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>     <span class="cf">for</span> k <span class="kw">in</span> idx]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La variable <code>pesos</code> tiene un tamaño de 21859 que corresponde al tamaño del vocabulario. Para concluir el ejemplo, se va a calcular el logaritmo de observar la frase <em>Buenos días</em>. Lo primero que se tiene que realizar es conocer la posición de cada segmento (e.g., palabra) en el vector <code>pesos</code> esto se realiza con la asociación mostrada en <code>idx2pos</code>. Lo segundo es crear un vector de ceros (i.e., <code>vec</code>) que contendrá la frase segmentadas. El tercer paso es segmentar la frase, iterar por cada segmento y agregar uno en la posición que corresponde a cada segmento en <code>vec</code>. El resultado es que <code>vec</code> tiene codificada la frase tal y como la realiza <code>ModeloNGram.</code></p>
<div id="28d75da6" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>idx2pos <span class="op">=</span> {k: v <span class="cf">for</span> v, k <span class="kw">in</span> <span class="bu">enumerate</span>(idx)}</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>vec <span class="op">=</span> np.zeros(<span class="bu">len</span>(pesos))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> seg <span class="kw">in</span> modelo.segmentar(<span class="st">'Buenos días'</span>):</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    vec[idx2pos[<span class="ss">f'</span><span class="sc">{</span>seg<span class="sc">}</span><span class="ss">'</span>]] <span class="op">+=</span> <span class="dv">1</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Con la información de <code>vec</code> y <code>pesos</code> se puede calcular el logaritmo de la probabilidad el cual corresponde al producto punto entre <code>vec</code> y <code>pesos</code> tal como se muestra en la siguiente instrucción.</p>
<div id="768afc11" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ss">f'</span><span class="sc">{</span>np<span class="sc">.</span>dot(vec, pesos)<span class="sc">:0.4f}</span><span class="ss">'</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>'-23.0646'</code></pre>
</div>
</div>
<p>Se puede verificar que el valor de <code>modelo._log_prob("Buenos días")</code> corresponde a -23.0646, que es equivalente al encontrado por la representación alternativa.</p>
<p>Se observa que la variable <code>vec</code> y <code>pesos</code> se pueden considerar como vectores que están <span class="math inline">\(\mathbb R^d\)</span> donde <span class="math inline">\(d\)</span> tiene un valor de 21859; por otro lado, la frase <em>Buenos días</em> está codificada en <code>vec</code>, haciendo que esta este representada como un vector en <span class="math inline">\(\mathbb R.\)</span></p>
</section>
<section id="bolsa-de-palabras-dispersa" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="bolsa-de-palabras-dispersa"><span class="header-section-number">5.2</span> Bolsa de Palabras Dispersa</h2>
<p>La idea anterior se podría considerar como una bolsa de palabras, donde cada término o segmento de palabra <span class="math inline">\(t\)</span> está asociado a un vector único <span class="math inline">\(\mathbf{v_t} \in \mathbb R^d\)</span> donde la <span class="math inline">\(i\)</span>-ésima componente, i.e., <span class="math inline">\(\mathbf{v_t}_i\)</span>, es diferente de cero y <span class="math inline">\(\forall_{j \neq i} \mathbf{v_t}_j=0\)</span>. Es decir la <span class="math inline">\(i\)</span>-ésima componente está asociada al término <span class="math inline">\(t\)</span>, se podría pensar que si el vocabulario está ordenado de alguna manera, entonces <span class="math inline">\(t\)</span> está en la posición <span class="math inline">\(i\)</span>. Por otro lado el valor que contiene la componente se usa para representar alguna característica del término.</p>
<p>El conjunto de vectores <span class="math inline">\(\mathbf v\)</span> corresponde al vocabulario, teniendo <span class="math inline">\(d\)</span> diferentes token en el mismo y por definición <span class="math inline">\(\forall_{i \neq j} \mathbf{v_i} \cdot \mathbf{v_j} = 0\)</span>, donde <span class="math inline">\(\mathbf{v_i} \in \mathbb R^d\)</span>, <span class="math inline">\(\mathbf{v_j} \in \mathbb R^d\)</span>, y <span class="math inline">\((\cdot)\)</span> es el producto punto. Cabe mencionar que cualquier segmento fuera del vocabulario es descartado.</p>
<p>Usando esta notación, un texto <span class="math inline">\(x\)</span> está representado por una secuencia de términos, i.e., <span class="math inline">\((t_1, t_2, \ldots)\)</span>; la secuencia puede tener repeticiones es decir, <span class="math inline">\(t_j = t_k\)</span>. Utilizando la característica de que cada término está asociado a un vector <span class="math inline">\(\mathbf v\)</span>, se transforma la secuencia de términos a una secuencia de vectores (manteniendo las repeticiones), i.e., <span class="math inline">\((\mathbf{v_{t_1}}, \mathbf{v_{t_2}}, \ldots)\)</span>. Finalmente, el texto <span class="math inline">\(x\)</span> se representa como:</p>
<p><span id="eq-bolsa-palabras"><span class="math display">\[
\mathbf x = \frac{\sum_t \mathbf{v_t}}{\lVert \sum_t \mathbf{v_t} \rVert},
\tag{5.1}\]</span></span></p>
<p>donde la suma se hace para todos los elementos de la secuencia, <span class="math inline">\(\mathbf x \in \mathbb R^d\)</span>, y <span class="math inline">\(\lVert \mathbf w \rVert\)</span> es la norma Euclideana del vector <span class="math inline">\(\mathbf w.\)</span></p>
<div class="cell" data-file="fig/repr-bolsa-dispersa.dot" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-repr-texto-bolsa-dispersa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repr-texto-bolsa-dispersa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<svg width="672" height="480" viewbox="0.00 0.00 543.57 120.42" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 116.42)">
<title>G</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-116.42 539.57,-116.42 539.57,4 -4,4"></polygon>
<!-- Terminos -->
<g id="node1" class="node">
<title>Terminos</title>
<ellipse fill="none" stroke="black" cx="60.25" cy="-83" rx="60" ry="29.33"></ellipse>
<text text-anchor="middle" x="60.25" y="-87.2" font-family="Times,serif" font-size="14.00">Texto</text>
<text text-anchor="middle" x="60.25" y="-70.4" font-family="Times,serif" font-size="14.00">Segmentado</text>
</g>
<!-- A -->
<g id="node2" class="node">
<title>A</title>
<polygon fill="none" stroke="black" points="357.44,-72 278.48,-72 278.48,-36 357.44,-36 357.44,-72"></polygon>
<text text-anchor="middle" x="317.96" y="-49.8" font-family="Times,serif" font-size="14.00">Asociación</text>
</g>
<!-- Terminos&#45;&gt;A -->
<g id="edge1" class="edge">
<title>Terminos-&gt;A</title>
<path fill="none" stroke="black" d="M119.27,-76.42C164.2,-71.32 225.71,-64.35 268.13,-59.54"></path>
<polygon fill="black" stroke="black" points="268.67,-63 278.21,-58.39 267.88,-56.04 268.67,-63"></polygon>
<text text-anchor="middle" x="199.48" y="-75.2" font-family="Times,serif" font-size="14.00">Pre-entrenados</text>
</g>
<!-- Entrenamiento -->
<g id="node3" class="node">
<title>Entrenamiento</title>
<polygon fill="none" stroke="black" points="238.97,-46.6 160,-46.6 160,-5.4 238.97,-5.4 238.97,-46.6"></polygon>
<text text-anchor="middle" x="199.48" y="-30.2" font-family="Times,serif" font-size="14.00">Estimación</text>
<text text-anchor="middle" x="199.48" y="-13.4" font-family="Times,serif" font-size="14.00"> de Pesos</text>
</g>
<!-- Terminos&#45;&gt;Entrenamiento -->
<g id="edge2" class="edge">
<title>Terminos-&gt;Entrenamiento</title>
<path fill="none" stroke="black" d="M106.57,-64.18C120.52,-58.38 135.94,-51.98 150.09,-46.1"></path>
<polygon fill="black" stroke="black" points="151.76,-49.2 159.65,-42.13 149.08,-42.73 151.76,-49.2"></polygon>
</g>
<!-- Repr -->
<g id="node5" class="node">
<title>Repr</title>
<ellipse fill="none" stroke="black" cx="465.01" cy="-54" rx="70.63" ry="18"></ellipse>
<text text-anchor="middle" x="465.01" y="-49.8" font-family="Times,serif" font-size="14.00">Representación</text>
</g>
<!-- A&#45;&gt;Repr -->
<g id="edge5" class="edge">
<title>A-&gt;Repr</title>
<path fill="none" stroke="black" d="M357.45,-54C365.77,-54 374.86,-54 384.12,-54"></path>
<polygon fill="black" stroke="black" points="384.2,-57.5 394.2,-54 384.2,-50.5 384.2,-57.5"></polygon>
</g>
<!-- Entrenamiento&#45;&gt;A -->
<g id="edge4" class="edge">
<title>Entrenamiento-&gt;A</title>
<path fill="none" stroke="black" d="M239.27,-35.32C248.6,-37.57 258.68,-39.99 268.4,-42.33"></path>
<polygon fill="black" stroke="black" points="267.8,-45.78 278.34,-44.72 269.44,-38.98 267.8,-45.78"></polygon>
</g>
<!-- Corpus -->
<g id="node4" class="node">
<title>Corpus</title>
<ellipse fill="none" stroke="black" cx="60.25" cy="-18" rx="38.87" ry="18"></ellipse>
<text text-anchor="middle" x="60.25" y="-13.8" font-family="Times,serif" font-size="14.00">Corpus</text>
</g>
<!-- Corpus&#45;&gt;Entrenamiento -->
<g id="edge3" class="edge">
<title>Corpus-&gt;Entrenamiento</title>
<path fill="none" stroke="black" stroke-dasharray="5,2" d="M99.11,-20.21C114.75,-21.12 133.07,-22.19 149.7,-23.16"></path>
<polygon fill="black" stroke="black" points="149.6,-26.66 159.79,-23.74 150.01,-19.67 149.6,-26.66"></polygon>
</g>
</g>
</svg>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repr-texto-bolsa-dispersa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.1: Diagrama Bolsa de Palabras Dispersa
</figcaption>
</figure>
</div>
</div>
</div>
<p>Antes de iniciar la descripción detallada del proceso de representación utilizando una bolsa de palabras dispersas, es conveniente ilustrar este proceso mediante la <a href="#fig-repr-texto-bolsa-dispersa" class="quarto-xref">Figura&nbsp;<span>5.1</span></a>. El <strong>texto segmentado</strong> es el resultado del proceso ilustrado en <a href="02ManejandoTexto.html#fig-pre-procesamiento" class="quarto-xref">Figura&nbsp;<span>2.1</span></a>. El texto segmentado puede seguir dos caminos, en la parte superior se encuentra el caso cuando los pesos han sido identificados previamente y en la parte inferior es el procedimiento cuando los pesos se estiman mediante un corpus específico que normalmente es un conjunto de entrenamiento.</p>
<section id="pesado-de-términos" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="pesado-de-términos"><span class="header-section-number">5.2.1</span> Pesado de Términos</h3>
<p>Como se había mencionado el valor que tiene la componente <span class="math inline">\(i\)</span>-ésima del vector <span class="math inline">\(\mathbf{v_t}_i\)</span> corresponde a una característica del término asociado, este procedimiento se le conoce como el <strong>esquema de pesado</strong>. Por ejemplo, si el valor es <span class="math inline">\(1\)</span> (i.e., <span class="math inline">\(\mathbf{v_{t_i}} = 1\)</span>) entonces el valor está indicando solo la presencia del término, este es el caso más simple. Considerando la <a href="#eq-bolsa-palabras" class="quarto-xref">Ecuación&nbsp;<span>5.1</span></a> se observa que el resultado, <span class="math inline">\(\mathbf x\)</span>, cuenta las repeticiones de cada término, por esta característica a este esquema se le conoce como <strong>frecuencia de términos</strong> (<em>term frequency (TF)</em>).</p>
<p>Una medida que complementa la información que tiene la frecuencia de términos es el inverso de la frecuencia del término (<em>Inverse Document Frequency (IDF)</em>) en la colección, esta medida propuesta por <span class="citation" data-cites="Jones1972">Sparck Jones (<a href="11Referencias.html#ref-Jones1972" role="doc-biblioref">1972</a>)</span> se usa en un método de pesado descrito por <span class="citation" data-cites="Salton1973">Salton y Yang (<a href="11Referencias.html#ref-Salton1973" role="doc-biblioref">1973</a>)</span> el cual es conocido como <strong>TFIDF</strong>. Este método de pesado propone el considerar el producto de la frecuencia del término y el inverso de la frecuencia del término (<em>Inverse Document Frequency (IDF)</em> ) en la colección como el peso del término.</p>
</section>
<section id="sec-bolsa-dispersa-ejemplos" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="sec-bolsa-dispersa-ejemplos"><span class="header-section-number">5.2.2</span> Ejemplos</h3>
<p>En los siguientes ejemplos se usa una bolsa de palabras con un pesado TFIDF pre-entrenada, los datos de esta bolsa de palabras se encuentra en el atributo <code>BoW.bow</code>. El tamaño del vocabulario es <span class="math inline">\(131072\)</span>, que está compuesto por palabras, gramas de palabras y caracteres. En el siguiente ejemplo se muestran los primeros tres gramas con sus respectivos valores TFIDF de la frase <em>Buen día</em>. Se puede observar que el <code>tm</code> regresa una lista de pares, donde la primera parte es el identificador del término, e.g., <span class="math inline">\(11219\)</span> y el segundo es el valor TFIDF, e.g., <span class="math inline">\(0.3984\)</span>. La lista tiene un tamaño de <span class="math inline">\(27\)</span> elementos, el resto de los <span class="math inline">\(131072\)</span> componentes son cero dado que no se encuentran en el texto representado.</p>
<div id="fc9a7bc4" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>bow <span class="op">=</span> BoW(lang<span class="op">=</span><span class="st">'es'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>tm <span class="op">=</span> bow.bow</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>vec <span class="op">=</span> tm[<span class="st">'Buen día'</span>]</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>vec[:<span class="dv">3</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>[(11219, np.float64(0.39843362852631786)),
 (11018, np.float64(0.3245843730253676)),
 (24409, np.float64(0.23778568902806235))]</code></pre>
</div>
</div>
<p>El uso del identificador del término se puede reemplazar por el término para poder visualizar mejor la representación del texto en el espacio vectorial. El diccionario que se encuentra en <code>BoW.names</code> hace la relación identificador a término. Se puede ver que el primer elemento del vector es el bigrama <em>buen~dia</em>, seguido por <em>buen</em> y el tercer término es <em>dia</em>. Los siguientes términos que no se muestran corresponden a gramas de caracteres. El valor TFIDF no indica la importancia del término, mientras mayor sea el valor, se considera más importante de acuerdo al TFIDF. En este ejemplo el bigrama tiene más importancia que las palabras y la palabra <em>buen</em> es más significativa que <em>dia</em>.</p>
<div id="0c5991c9" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>[(bow.names[k], v)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a> <span class="cf">for</span> k, v <span class="kw">in</span> vec[:<span class="dv">3</span>]]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>[('buen~dia', np.float64(0.39843362852631786)),
 ('buen', np.float64(0.3245843730253676)),
 ('dia', np.float64(0.23778568902806235))]</code></pre>
</div>
</div>
<p>Con el objetivo de ilustrar una heurística que ha dado buenos resultados en el siguiente ejemplo se presentan las primeras cuatro componentes del texto <em>Buen día colegas</em>. Se puede observar como los valores de IDF de los términos comunes cambiaron, por ejemplo para el caso de <em>buen~dia</em> cambio de <span class="math inline">\(0.3984\)</span> a <span class="math inline">\(0.2486\)</span>. Este es el resultado de que los valores están normalizados tal como se muestra en la <a href="#eq-bolsa-palabras" class="quarto-xref">Ecuación&nbsp;<span>5.1</span></a>. Por otro lado, se observa que ahora el término más significativo es la palabra <em>colegas</em>.</p>
<div id="88f87b71" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>txt <span class="op">=</span> <span class="st">'Buen día colegas'</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>[(tm.id2token[k], v)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a> <span class="cf">for</span> k, v <span class="kw">in</span> tm[txt][:<span class="dv">4</span>]]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>[('buen~dia', np.float64(0.24862785236357487)),
 ('buen', np.float64(0.20254494048246244)),
 ('dia', np.float64(0.1483814139998851)),
 ('colegas', np.float64(0.3538047214393573))]</code></pre>
</div>
</div>
<p>Una manera de visualizar la representación es creando una nube de palabras de los términos, donde el tamaño del termino corresponde al valor TFIDF. En la <a href="#fig-repr-texto-nube" class="quarto-xref">Figura&nbsp;<span>5.2</span></a> muestra la nube de palabras generada con los términos y sus respectivos valores IDF del texto <em>Es un placer estar platicando con ustedes.</em></p>
<div id="cell-fig-repr-texto-nube" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>txt <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>tokens <span class="op">=</span> {tm.id2token[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> tm[txt]}</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>word_cloud <span class="op">=</span> WordCloud().generate_from_frequencies(tokens)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>plt.imshow(word_cloud, interpolation<span class="op">=</span><span class="st">'bilinear'</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">False</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plt.tick_params(left<span class="op">=</span><span class="va">False</span>, right<span class="op">=</span><span class="va">False</span>, labelleft<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                labelbottom<span class="op">=</span><span class="va">False</span>, bottom<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-repr-texto-nube" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repr-texto-nube-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05RepresentacionTexto_files/figure-html/fig-repr-texto-nube-output-1.png" width="540" height="280" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repr-texto-nube-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.2: Nube de términos
</figcaption>
</figure>
</div>
</div>
</div>
<p>El texto se representa en un espacio vectorial, entonces es posible comparar la similitud entre dos textos en esta representación, por ejemplo, en el siguiente ejemplo se compara la similitud coseno entre los textos <em>Es un placer estar platicando con ustedes.</em> y <em>La lluvia genera un caos en la ciudad.</em> El valor obtenido es cercano a cero indicando que estos textos no son similares.</p>
<div id="a525d851" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>txt2 <span class="op">=</span> <span class="st">'La lluvia genera un caos en la ciudad.'</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>vec1 <span class="op">=</span> tm[txt1]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>vec2 <span class="op">=</span> tm[txt2]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> {k: v <span class="cf">for</span> k, v <span class="kw">in</span> vec1}</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>([f[k] <span class="op">*</span> v <span class="cf">for</span> k, v <span class="kw">in</span> vec2 <span class="cf">if</span> k <span class="kw">in</span> f])</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>np.float64(0.016455192944786954)</code></pre>
</div>
</div>
<p>Complementando el ejemplo anterior, en esta ocasión se comparan dos textos que comparten el concepto <em>plática</em>, estos son <em>Es un placer estar platicando con ustedes.</em> y <em>Estoy dando una platica en Morelia.</em> se puede observar que estos textos son más similares que los ejemplos anteriores.</p>
<div id="f84249d6" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>txt2 <span class="op">=</span> <span class="st">'Estoy dando una platica en Morelia.'</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>vec1 <span class="op">=</span> tm[txt1]</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>vec2 <span class="op">=</span> tm[txt2]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> {k: v <span class="cf">for</span> k, v <span class="kw">in</span> vec1}</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>([f[k] <span class="op">*</span> v <span class="cf">for</span> k, v <span class="kw">in</span> vec2 <span class="cf">if</span> k <span class="kw">in</span> f])</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>np.float64(0.2035427118119316)</code></pre>
</div>
</div>
<p>Habiendo realizado la similitud entre algunos textos lleva a preguntarse cómo será la distribución de similitud entre varios textos, para poder contestar esta pregunta, se utilizarán los datos de <a href="https://ingeotec.github.io/Delitos">Delitos</a>, los cuales se guardan en la variable <code>D</code> tal y como se en las siguientes instrucciones.</p>
<div id="db3bb71b" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fname <span class="op">=</span> <span class="st">'delitos/delitos_ingeotec_Es_train.json'</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> <span class="bu">list</span>(tweet_iterator(fname))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>El primer paso es representar todos los textos en el espacio vectorial de la bolsa de palabras, lo cual se logra con el método <code>BoW.transform</code> (primera linea), el segundo paso es calcular la similitud entre todos los textos, como se muestra en la segunda linea.</p>
<div id="ec552046" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> tm.transform(D)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>sim <span class="op">=</span> np.dot(X, X.T)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La distribución de similitud se muestra en la <a href="#fig-text-repr-similitud-bow" class="quarto-xref">Figura&nbsp;<span>5.3</span></a> se puede observar que las similitudes se encuentran concentradas cerca del cero, esto indica que la mayoría de los textos están distantes, esto es el resultado de la bolsa de palabras discreta que se enfoca en modelar las palabras y no el significado de las mismas.</p>
<div id="cell-fig-text-repr-similitud-bow" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sns.displot(sim.data)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-text-repr-similitud-bow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-text-repr-similitud-bow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05RepresentacionTexto_files/figure-html/fig-text-repr-similitud-bow-output-1.png" width="469" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-text-repr-similitud-bow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.3: Histograma de la similitud
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="bolsa-de-palabras-densa" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="bolsa-de-palabras-densa"><span class="header-section-number">5.3</span> Bolsa de Palabras Densa</h2>
<p>La <a href="#fig-repr-texto-bolsa-densa" class="quarto-xref">Figura&nbsp;<span>5.4</span></a> muestra el procedimiento que se sigue para representar un texto en una bolsa de palabras dispersa. En primer lugar la bolsa de palabras densa considera que los vectores asociados a los términos se encuentra pre-entrenados y en general no es factible entrenarlos en el momento, esto por el tiempo que lleva estimar estos vectores.</p>
<div class="cell" data-file="fig/repr-bolsa-densa.dot" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-repr-texto-bolsa-densa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repr-texto-bolsa-densa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<svg width="672" height="480" viewbox="0.00 0.00 505.57 66.83" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 62.83)">
<title>G</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-62.83 501.57,-62.83 501.57,4 -4,4"></polygon>
<!-- Terminos -->
<g id="node1" class="node">
<title>Terminos</title>
<ellipse fill="none" stroke="black" cx="60.25" cy="-29.42" rx="60" ry="29.33"></ellipse>
<text text-anchor="middle" x="60.25" y="-33.62" font-family="Times,serif" font-size="14.00">Texto</text>
<text text-anchor="middle" x="60.25" y="-16.82" font-family="Times,serif" font-size="14.00">Segmentado</text>
</g>
<!-- A -->
<g id="node2" class="node">
<title>A</title>
<polygon fill="none" stroke="black" points="319.44,-47.42 240.48,-47.42 240.48,-11.42 319.44,-11.42 319.44,-47.42"></polygon>
<text text-anchor="middle" x="279.96" y="-25.22" font-family="Times,serif" font-size="14.00">Asociación</text>
</g>
<!-- Terminos&#45;&gt;A -->
<g id="edge1" class="edge">
<title>Terminos-&gt;A</title>
<path fill="none" stroke="black" d="M120.74,-29.42C155.16,-29.42 197.94,-29.42 230.33,-29.42"></path>
<polygon fill="black" stroke="black" points="230.46,-32.92 240.46,-29.42 230.46,-25.92 230.46,-32.92"></polygon>
<text text-anchor="middle" x="180.48" y="-33.62" font-family="Times,serif" font-size="14.00">Pre-entrenados</text>
</g>
<!-- Repr -->
<g id="node3" class="node">
<title>Repr</title>
<ellipse fill="none" stroke="black" cx="427.01" cy="-29.42" rx="70.63" ry="18"></ellipse>
<text text-anchor="middle" x="427.01" y="-25.22" font-family="Times,serif" font-size="14.00">Representación</text>
</g>
<!-- A&#45;&gt;Repr -->
<g id="edge2" class="edge">
<title>A-&gt;Repr</title>
<path fill="none" stroke="black" d="M319.45,-29.42C327.77,-29.42 336.86,-29.42 346.12,-29.42"></path>
<polygon fill="black" stroke="black" points="346.2,-32.92 356.2,-29.42 346.2,-25.92 346.2,-32.92"></polygon>
</g>
</g>
</svg>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repr-texto-bolsa-densa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.4: Diagrama Bolsa de Palabras Densa
</figcaption>
</figure>
</div>
</div>
</div>
<p>El texto se representa como el vector <span class="math inline">\(\mathbf u\)</span> que se calcula usando la <a href="#eq-bolsa-densas" class="quarto-xref">Ecuación&nbsp;<span>5.2</span></a> donde se observa que es la suma de los vectores asociados a cada término más un coeficiente <span class="math inline">\(\mathbf{w_0}\)</span>. En particular el coeficiente <span class="math inline">\(\mathbf{w_0} \in \mathbb R^{M}\)</span> no se encuentra en todas las representaciones densas, pero en la representación que se usará contiene este vector, <span class="math inline">\(M\)</span> es la dimensión de la representación densa.</p>
<p><span id="eq-bolsa-densas"><span class="math display">\[
\mathbf u = \sum_t \mathbf{u_t} + \mathbf{w_0}.
\tag{5.2}\]</span></span></p>
<p>En vector <span class="math inline">\(\mathbf {u_t}\)</span> está asociado al término <span class="math inline">\(t\)</span>, en particular este vector en la representación densa que se describirá está definido en términos de una bolsa de palabras dispersa (<a href="#eq-bolsa-palabras" class="quarto-xref">Ecuación&nbsp;<span>5.1</span></a>) como se puede observar en la <a href="#eq-bolsa-densa-ut" class="quarto-xref">Ecuación&nbsp;<span>5.3</span></a></p>
<p><span id="eq-bolsa-densa-ut"><span class="math display">\[
\mathbf{u_t} = \frac{\mathbf W \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert},
\tag{5.3}\]</span></span></p>
<p>donde <span class="math inline">\(\mathbf W \in \mathbb R^{M \times d}\)</span> es la matriz que hace la proyección de la representación dispersa a la representación densa, se puede observar esa operación está normalizada con la norma Euclideana de la representación dispersa.</p>
<p>Combinando las <a href="#eq-bolsa-densas" class="quarto-xref">Ecuación&nbsp;<span>5.2</span></a> y <a href="#eq-bolsa-densa-ut" class="quarto-xref">Ecuación&nbsp;<span>5.3</span></a> queda la</p>
<p><span class="math display">\[
\begin{split}
\mathbf{u_t} &amp;= \sum_t \frac{\mathbf W \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert} + \mathbf{w_0} \\
&amp;= \mathbf W \frac{\sum_t \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert} + \mathbf{w_0},
\end{split}
\]</span></p>
<p>donde se puede observar la representación dispersa (<a href="#eq-bolsa-palabras" class="quarto-xref">Ecuación&nbsp;<span>5.1</span></a>), i.e., <span class="math inline">\(\frac{\sum_t \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert}\)</span> lo cual resulta en la <a href="#eq-bolsa-densa-texto" class="quarto-xref">Ecuación&nbsp;<span>5.4</span></a></p>
<p><span id="eq-bolsa-densa-texto"><span class="math display">\[
\mathbf u = \mathbf W \mathbf x + \mathbf{w_0},
\tag{5.4}\]</span></span></p>
<p>que representa un texto en el vector <span class="math inline">\(\mathbf u \in \mathbb R^M.\)</span></p>
<p>Para algunas representaciones densas, las componentes de la matriz de transformación <span class="math inline">\(\mathcal W\)</span> están asociadas a conceptos, en el caso que se analiza estas están asociadas a palabras claves o emojis.</p>
<section id="ejemplos" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="ejemplos"><span class="header-section-number">5.3.1</span> Ejemplos</h3>
<p>Continuando con los ejemplos presentados para la bolsa dispersa (<a href="#sec-bolsa-dispersa-ejemplos" class="quarto-xref"><span>Sección 5.2.2</span></a>) en esta sección se hace el análisis con la representación de palabras densa. El primer paso es inicializar la clase que contiene las representaciones densas, esto se hace con la siguiente instrucción.</p>
<div id="bc02a2a5" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dense <span class="op">=</span> DenseBoW(lang<span class="op">=</span><span class="st">'es'</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                 voc_size_exponent<span class="op">=</span><span class="dv">15</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                 emoji<span class="op">=</span><span class="va">False</span>, keyword<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                 distance_hyperplane<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                 dataset<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Para representar un texto en el espacio vectorial denso se utiliza el método <code>transform</code>, por ejemplo la siguiente instrucción representa el texto <em>Es un placer estar platicando con ustedes.</em> Solo se visualizan los valores de las primeras tres componentes.</p>
<div id="1f156087" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>dense.transform([txt1])[<span class="dv">0</span>, :<span class="dv">3</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>array([-0.0042934 , -0.00429635, -0.00515905])</code></pre>
</div>
</div>
<p>Lo primero que se observa es que los valores son negativos, a diferencia del caso disperso donde todos los valores son positivos. En este tipo de representación cada componente está asociada a una palabra las cuales se pueden conocer en el atributo <code>names</code>. El siguiente código muestra las tres primeras palabras asociadas al ejemplo anterior.</p>
<div id="ba9272fd" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dense.names[:<span class="dv">3</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>[np.str_('semanas'), np.str_('cuatro'), np.str_('piensa')]</code></pre>
</div>
</div>
<p>Siguiente la idea de utilizar una nube de palabras para visualizar el vector que representa el texto modelado, La <a href="#fig-repr-texto-nube-densa" class="quarto-xref">Figura&nbsp;<span>5.5</span></a> muestra las nubes de palabras generada con las características y sus respectivos valores del texto <em>Es un placer estar platicando con ustedes.</em> Durante la generación de la nube de palabras se decidió representar genera una nube de palabras con las palabras con coeficiente negativo más significativo y aquellas con los coeficientes positivos más significativos. Se puede observar que las palabras positivas contienen componentes que están relacionados al enunciado, pero al mismo tiempo leyendo los términos positivos es complicado construir el texto representado. Adicionalmente las términos negativos que se observan en la nube de palabras en su mayoría son hashtags que tiene muy poca relación al texto representado.</p>
<div id="cell-fig-repr-texto-nube-densa" class="cell" data-execution_count="23">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> dense.transform([txt1])</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> dense.names</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>tokens_pos <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">0</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>tokens_neg <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="op">*</span> <span class="op">-</span><span class="dv">1</span> <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">0</span>]) <span class="cf">if</span> v <span class="op">&lt;</span> <span class="dv">0</span>}</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>word_pos <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_pos)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>word_neg <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_neg)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cloud, ax, title <span class="kw">in</span> <span class="bu">zip</span>([word_neg, word_pos],</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>                     [ax1, ax2],</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>                     [<span class="st">'Negativas'</span>, </span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Positivas'</span>]):</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    ax.imshow(cloud, interpolation<span class="op">=</span><span class="st">'bilinear'</span>)</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">False</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(left<span class="op">=</span><span class="va">False</span>, right<span class="op">=</span><span class="va">False</span>, labelleft<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>                   labelbottom<span class="op">=</span><span class="va">False</span>, bottom<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-repr-texto-nube-densa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repr-texto-nube-densa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05RepresentacionTexto_files/figure-html/fig-repr-texto-nube-densa-output-1.png" width="540" height="158" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repr-texto-nube-densa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.5: Nube de características para el texto <em>Es un placer estar platicando con ustedes.</em>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Esta representación también permite comparación de similitud entre textos, en el siguiente ejemplo se calcula la similitud entre el texto <em>Es un placer estar platicando con ustedes.</em> y los textos <em>La lluvia genera un caos en la ciudad.</em> y <em>Estoy dando una platica en Morelia.</em> tal y como se hizo para la representación dispersa. Se puede observar que existe una mayor similitud entre los textos que contienen el concepto <strong>plática</strong>, lo cual es equivalente a lo que se observó en el ejemplo con bolsa de palabras discretas, pero los valores son significativamente mayores que en ese caso.</p>
<div id="975f6f5d" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>txt2 <span class="op">=</span> <span class="st">'La lluvia genera un caos en la ciudad.'</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>txt3 <span class="op">=</span> <span class="st">'Estoy dando una platica en Morelia.'</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> dense.transform([txt1, txt2, txt3])</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>np.dot(X[<span class="dv">0</span>], X[<span class="dv">1</span>]), np.dot(X[<span class="dv">0</span>], X[<span class="dv">2</span>])</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>(np.float64(0.7728943423183761), np.float64(0.8721107462230384))</code></pre>
</div>
</div>
<p>Los valores de similitud entre los enunciados anteriores, se puede visualizar en una nube de palabras, utilizando solo las características positivas. La <a href="#fig-repr-texto-nube-densa-comp" class="quarto-xref">Figura&nbsp;<span>5.6</span></a> muestra las nubes de palabras generadas, en ellas es complicado comprender la razón por la cual la frases que tiene el concepto <em>plática</em> están más cercanas, es probable que la cola de la distribución, es decir, las palabras menos significativas son las que acercan las dos oraciones.</p>
<div id="cell-fig-repr-texto-nube-densa-comp" class="cell" data-execution_count="25">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> dense.transform([txt1, txt2, txt3])</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> dense.names</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>tokens_pos <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">0</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>tokens_neg <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">1</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>tokens_otro <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">2</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>word_pos <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_pos)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>word_neg <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_neg)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>word_otro <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_otro)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2, ax3) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cloud, ax, title <span class="kw">in</span> <span class="bu">zip</span>([word_pos, word_neg, word_otro],</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>                     [ax1, ax2, ax3],</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>                     [<span class="st">'Es un ... ustedes.'</span>, </span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'La lluvia ... ciudad.'</span>,</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Estoy ... Morelia.'</span>]):</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    ax.imshow(cloud, interpolation<span class="op">=</span><span class="st">'bilinear'</span>)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">False</span>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(left<span class="op">=</span><span class="va">False</span>, right<span class="op">=</span><span class="va">False</span>, labelleft<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>                   labelbottom<span class="op">=</span><span class="va">False</span>, bottom<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-repr-texto-nube-densa-comp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repr-texto-nube-densa-comp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05RepresentacionTexto_files/figure-html/fig-repr-texto-nube-densa-comp-output-1.png" width="540" height="116" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repr-texto-nube-densa-comp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.6: Nube de características positivas.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Al igual que en el caso disperso se puede calcular la distribución de similitud. Las siguientes instrucciones calcula la similitud coseno entre todos los ejemplos del conjunto de entrenamiento (<span class="math inline">\(\mathcal T\)</span>).</p>
<div id="c41b7f81" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> dense.transform(D)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>sim <span class="op">=</span> np.dot(X, X.T)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La <a href="#fig-text-repr-similitud-dense" class="quarto-xref">Figura&nbsp;<span>5.7</span></a> muestra el histograma de las similitudes calculada mediante la bolsa densa. Aquí se puede observar que la gran mayoría de los ejemplos tiene una similitud mayor y tiene una desviación estándar mayor que la vista en la <a href="#fig-text-repr-similitud-bow" class="quarto-xref">Figura&nbsp;<span>5.3</span></a>.</p>
<div id="cell-fig-text-repr-similitud-dense" class="cell" data-execution_count="27">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>sns.displot(sim.flatten())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-text-repr-similitud-dense" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-text-repr-similitud-dense-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05RepresentacionTexto_files/figure-html/fig-text-repr-similitud-dense-output-1.png" width="469" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-text-repr-similitud-dense-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5.7: Histograma de la similitud usando bolsa de palabras densas
</figcaption>
</figure>
</div>
</div>
</div>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Salton1973" class="csl-entry" role="listitem">
Salton, Gerard, y Chungshu S. Yang. 1973. <span>«On the specification of term values in automatic indexing»</span>. <em>Journal of Documentation</em> 29 (abril): 351-72. <a href="https://doi.org/10.1108/EB026562">https://doi.org/10.1108/EB026562</a>.
</div>
<div id="ref-Jones1972" class="csl-entry" role="listitem">
Sparck Jones, Karen. 1972. <span>«A statistical interpretation of term specificity and its application in retrieval»</span>. <em>Journal of Documentation</em> 28: 11-21. <a href="https://doi.org/10.1108/EB026526">https://doi.org/10.1108/EB026526</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ingeotec\.github\.io\/PLN");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            trigger: 'click',
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            positionFixed: true,
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../capitulos/04FundamentosCT.html" class="pagination-link" aria-label="Fundamentos de Clasificación de Texto">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Fundamentos de Clasificación de Texto</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../capitulos/06ClasificacionTexto.html" class="pagination-link" aria-label="Clasificación de Texto">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Clasificación de Texto</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Representación de Texto</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>El **objetivo** de la unidad es analizar diferentes representaciones de texto basadas en vectores. </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## Paquetes usados {.unnumbered}</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> EvoMSA <span class="im">import</span> BoW,<span class="op">\</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>                   DenseBoW</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> microtc.utils <span class="im">import</span> tweet_iterator</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> wordcloud <span class="im">import</span> WordCloud                            </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pylab <span class="im">as</span> plt</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">'whitegrid'</span>)</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: false</span></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> Counter</span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> os.path <span class="im">import</span> isfile, isdir</span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> AutoTokenizer</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> encexp.utils <span class="im">import</span> load_dataset</span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> EvoMSA.utils <span class="im">import</span> Download</span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> EvoMSA <span class="im">import</span> utils</span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>utils.USE_TQDM <span class="op">=</span> <span class="va">False</span></span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> isfile(<span class="st">'delitos.zip'</span>):</span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>    Download(<span class="st">'https://github.com/INGEOTEC/Delitos/releases/download/Datos/delitos.zip'</span>,</span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a>             <span class="st">'delitos.zip'</span>)</span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> isdir(<span class="st">'delitos'</span>):</span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a>    <span class="op">!</span>unzip <span class="op">-</span>Pingeotec delitos.<span class="bu">zip</span></span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-53"><a href="#cb32-53" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb32-54"><a href="#cb32-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-55"><a href="#cb32-55" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Frec:</span>
<span id="cb32-56"><a href="#cb32-56" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, N: <span class="bu">int</span><span class="op">=</span><span class="dv">2</span>):</span>
<span id="cb32-57"><a href="#cb32-57" aria-hidden="true" tabindex="-1"></a>    <span class="va">self</span>.N <span class="op">=</span> N <span class="co"># &lt;1&gt;</span></span>
<span id="cb32-58"><a href="#cb32-58" aria-hidden="true" tabindex="-1"></a>    <span class="va">self</span>.voc <span class="op">=</span> Counter()</span>
<span id="cb32-59"><a href="#cb32-59" aria-hidden="true" tabindex="-1"></a>    <span class="va">self</span>.frase <span class="op">=</span> Counter()</span>
<span id="cb32-60"><a href="#cb32-60" aria-hidden="true" tabindex="-1"></a>    <span class="va">self</span>.hist <span class="op">=</span> Counter()</span>
<span id="cb32-61"><a href="#cb32-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-62"><a href="#cb32-62" aria-hidden="true" tabindex="-1"></a>  <span class="at">@property</span></span>
<span id="cb32-63"><a href="#cb32-63" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> segmentador(<span class="va">self</span>):</span>
<span id="cb32-64"><a href="#cb32-64" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb32-65"><a href="#cb32-65" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> <span class="va">self</span>._segmentador</span>
<span id="cb32-66"><a href="#cb32-66" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">AttributeError</span>:</span>
<span id="cb32-67"><a href="#cb32-67" aria-hidden="true" tabindex="-1"></a>      _ <span class="op">=</span> AutoTokenizer.from_pretrained(<span class="st">'guillermoruiz/bilmaLAT'</span>) <span class="co"># &lt;5&gt;</span></span>
<span id="cb32-68"><a href="#cb32-68" aria-hidden="true" tabindex="-1"></a>      <span class="va">self</span>._segmentador <span class="op">=</span> _</span>
<span id="cb32-69"><a href="#cb32-69" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> _</span>
<span id="cb32-70"><a href="#cb32-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-71"><a href="#cb32-71" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> fit(<span class="va">self</span>, X, y<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb32-72"><a href="#cb32-72" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="va">self</span>.N</span>
<span id="cb32-73"><a href="#cb32-73" aria-hidden="true" tabindex="-1"></a>    voc <span class="op">=</span> <span class="va">self</span>.voc</span>
<span id="cb32-74"><a href="#cb32-74" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ele <span class="kw">in</span> X:</span>
<span id="cb32-75"><a href="#cb32-75" aria-hidden="true" tabindex="-1"></a>      tokens <span class="op">=</span> <span class="va">self</span>.segmentar(ele)</span>
<span id="cb32-76"><a href="#cb32-76" aria-hidden="true" tabindex="-1"></a>      voc.update(tokens)</span>
<span id="cb32-77"><a href="#cb32-77" aria-hidden="true" tabindex="-1"></a>      _ <span class="op">=</span> [<span class="st">"|"</span>.join(<span class="bu">map</span>(<span class="bu">str</span>, lst))</span>
<span id="cb32-78"><a href="#cb32-78" aria-hidden="true" tabindex="-1"></a>          <span class="cf">for</span> lst <span class="kw">in</span> <span class="bu">zip</span>(<span class="op">*</span>[tokens[i:] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(N)])]</span>
<span id="cb32-79"><a href="#cb32-79" aria-hidden="true" tabindex="-1"></a>      <span class="va">self</span>.frase.update(_)</span>
<span id="cb32-80"><a href="#cb32-80" aria-hidden="true" tabindex="-1"></a>      _ <span class="op">=</span> [<span class="st">"|"</span>.join(<span class="bu">map</span>(<span class="bu">str</span>, lst))</span>
<span id="cb32-81"><a href="#cb32-81" aria-hidden="true" tabindex="-1"></a>          <span class="cf">for</span> lst <span class="kw">in</span> <span class="bu">zip</span>(<span class="op">*</span>[tokens[i:] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(N<span class="op">-</span><span class="dv">1</span>)])]</span>
<span id="cb32-82"><a href="#cb32-82" aria-hidden="true" tabindex="-1"></a>      <span class="va">self</span>.hist.update(_)</span>
<span id="cb32-83"><a href="#cb32-83" aria-hidden="true" tabindex="-1"></a>    <span class="va">self</span>.voc <span class="op">=</span> <span class="bu">len</span>(voc)</span>
<span id="cb32-84"><a href="#cb32-84" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> N <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb32-85"><a href="#cb32-85" aria-hidden="true" tabindex="-1"></a>      <span class="va">self</span>.hist <span class="op">=</span> <span class="bu">sum</span>(<span class="va">self</span>.frase.values())</span>
<span id="cb32-86"><a href="#cb32-86" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">self</span></span>
<span id="cb32-87"><a href="#cb32-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-88"><a href="#cb32-88" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> segmentar(<span class="va">self</span>, texto):</span>
<span id="cb32-89"><a href="#cb32-89" aria-hidden="true" tabindex="-1"></a>    _ <span class="op">=</span> <span class="va">self</span>.get_text(texto)</span>
<span id="cb32-90"><a href="#cb32-90" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">self</span>.segmentador(_).input_ids</span>
<span id="cb32-91"><a href="#cb32-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-92"><a href="#cb32-92" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> get_text(<span class="va">self</span>, ele):</span>
<span id="cb32-93"><a href="#cb32-93" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(ele, <span class="bu">dict</span>):</span>
<span id="cb32-94"><a href="#cb32-94" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> ele[<span class="st">'text'</span>]</span>
<span id="cb32-95"><a href="#cb32-95" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ele</span>
<span id="cb32-96"><a href="#cb32-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-97"><a href="#cb32-97" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> frecuencias(<span class="va">self</span>, code, log<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb32-98"><a href="#cb32-98" aria-hidden="true" tabindex="-1"></a>    num <span class="op">=</span> <span class="va">self</span>.frase[<span class="st">"|"</span>.join(<span class="bu">map</span>(<span class="bu">str</span>, code))]</span>
<span id="cb32-99"><a href="#cb32-99" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="va">self</span>.N <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb32-100"><a href="#cb32-100" aria-hidden="true" tabindex="-1"></a>      den <span class="op">=</span> <span class="va">self</span>.hist</span>
<span id="cb32-101"><a href="#cb32-101" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb32-102"><a href="#cb32-102" aria-hidden="true" tabindex="-1"></a>      den <span class="op">=</span> <span class="va">self</span>.hist[<span class="st">"|"</span>.join(<span class="bu">map</span>(<span class="bu">str</span>, code[:<span class="op">-</span><span class="dv">1</span>]))]</span>
<span id="cb32-103"><a href="#cb32-103" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> log: <span class="co"># &lt;14&gt;</span></span>
<span id="cb32-104"><a href="#cb32-104" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> np.log(num), np.log(den)</span>
<span id="cb32-105"><a href="#cb32-105" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> num, den</span>
<span id="cb32-106"><a href="#cb32-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-107"><a href="#cb32-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-108"><a href="#cb32-108" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Freck(Frec):</span>
<span id="cb32-109"><a href="#cb32-109" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, N: <span class="bu">int</span><span class="op">=</span><span class="dv">2</span>, k_suavizado: <span class="bu">float</span><span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb32-110"><a href="#cb32-110" aria-hidden="true" tabindex="-1"></a>    <span class="bu">super</span>(Freck, <span class="va">self</span>).<span class="fu">__init__</span>(N)</span>
<span id="cb32-111"><a href="#cb32-111" aria-hidden="true" tabindex="-1"></a>    <span class="va">self</span>.k_suavizado <span class="op">=</span> k_suavizado</span>
<span id="cb32-112"><a href="#cb32-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-113"><a href="#cb32-113" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> frecuencias(<span class="va">self</span>, code, log<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb32-114"><a href="#cb32-114" aria-hidden="true" tabindex="-1"></a>    num, den <span class="op">=</span> <span class="bu">super</span>(Freck, <span class="va">self</span>).frecuencias(code)</span>
<span id="cb32-115"><a href="#cb32-115" aria-hidden="true" tabindex="-1"></a>    num <span class="op">=</span> num <span class="op">+</span> <span class="va">self</span>.k_suavizado</span>
<span id="cb32-116"><a href="#cb32-116" aria-hidden="true" tabindex="-1"></a>    den <span class="op">=</span> den <span class="op">+</span> <span class="va">self</span>.k_suavizado <span class="op">*</span> <span class="va">self</span>.voc</span>
<span id="cb32-117"><a href="#cb32-117" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> log:</span>
<span id="cb32-118"><a href="#cb32-118" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> np.log(num), np.log(den)</span>
<span id="cb32-119"><a href="#cb32-119" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> num, den</span>
<span id="cb32-120"><a href="#cb32-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-121"><a href="#cb32-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-122"><a href="#cb32-122" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> ModeloNGram(Freck):</span>
<span id="cb32-123"><a href="#cb32-123" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, N: <span class="bu">int</span><span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb32-124"><a href="#cb32-124" aria-hidden="true" tabindex="-1"></a>               k_suavizado: <span class="bu">float</span><span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb32-125"><a href="#cb32-125" aria-hidden="true" tabindex="-1"></a>               promedio: <span class="bu">bool</span><span class="op">=</span><span class="va">False</span>):</span>
<span id="cb32-126"><a href="#cb32-126" aria-hidden="true" tabindex="-1"></a>    <span class="bu">super</span>(ModeloNGram, <span class="va">self</span>).<span class="fu">__init__</span>(N, k_suavizado)</span>
<span id="cb32-127"><a href="#cb32-127" aria-hidden="true" tabindex="-1"></a>    <span class="va">self</span>.promedio <span class="op">=</span> promedio</span>
<span id="cb32-128"><a href="#cb32-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-129"><a href="#cb32-129" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> _log_prob(<span class="va">self</span>, ele):</span>
<span id="cb32-130"><a href="#cb32-130" aria-hidden="true" tabindex="-1"></a>    tokens <span class="op">=</span> <span class="va">self</span>.segmentar(ele)</span>
<span id="cb32-131"><a href="#cb32-131" aria-hidden="true" tabindex="-1"></a>    acc <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb32-132"><a href="#cb32-132" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> code <span class="kw">in</span> <span class="bu">zip</span>(<span class="op">*</span>[tokens[i:] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="va">self</span>.N)]):</span>
<span id="cb32-133"><a href="#cb32-133" aria-hidden="true" tabindex="-1"></a>      num, den <span class="op">=</span> <span class="va">self</span>.frecuencias(code, log<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb32-134"><a href="#cb32-134" aria-hidden="true" tabindex="-1"></a>      acc <span class="op">+=</span> num <span class="op">-</span> den</span>
<span id="cb32-135"><a href="#cb32-135" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="va">self</span>.promedio:</span>
<span id="cb32-136"><a href="#cb32-136" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> acc <span class="op">/</span> <span class="bu">len</span>(tokens)</span>
<span id="cb32-137"><a href="#cb32-137" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> acc</span>
<span id="cb32-138"><a href="#cb32-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-139"><a href="#cb32-139" aria-hidden="true" tabindex="-1"></a>  <span class="kw">def</span> log_prob(<span class="va">self</span>, X):</span>
<span id="cb32-140"><a href="#cb32-140" aria-hidden="true" tabindex="-1"></a>    _log_prob <span class="op">=</span> <span class="va">self</span>._log_prob</span>
<span id="cb32-141"><a href="#cb32-141" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.r_[[_log_prob(x) <span class="cf">for</span> x <span class="kw">in</span> X]]</span>
<span id="cb32-142"><a href="#cb32-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-143"><a href="#cb32-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-144"><a href="#cb32-144" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introducción</span></span>
<span id="cb32-145"><a href="#cb32-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-146"><a href="#cb32-146" aria-hidden="true" tabindex="-1"></a>En el @sec-fund-cl-texto se describió un clasificador de texto que está basado en el modelo de lenguaje de gramas. Uno se podría imaginar que este clasificador representa de alguna manera al texto, es decir, que exite una estructura matemática donde los textos están representados. En este caso particular se observará que los textos están representados en un espacio vectorial. En los siguientes fragmentos de código se realizará una implementación equivalente que ayuda a visualizar esta representación.  </span>
<span id="cb32-147"><a href="#cb32-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-148"><a href="#cb32-148" aria-hidden="true" tabindex="-1"></a>Lo primer que se realiza es cargar el conjunto de datos que ha sido utilizado en el @sec-fund-cl-texto y se crea un modelo de lenguaje (i.e., <span class="in">`ModeloNGram`</span>) de unigramas y sin $k$-suavizado. </span>
<span id="cb32-149"><a href="#cb32-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-152"><a href="#cb32-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-153"><a href="#cb32-153" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-154"><a href="#cb32-154" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: false</span></span>
<span id="cb32-155"><a href="#cb32-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-156"><a href="#cb32-156" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> load_dataset(lang<span class="op">=</span><span class="st">'es'</span>, dataset<span class="op">=</span><span class="st">'dev'</span>)</span>
<span id="cb32-157"><a href="#cb32-157" aria-hidden="true" tabindex="-1"></a>modelo <span class="op">=</span> ModeloNGram(N<span class="op">=</span><span class="dv">1</span>, k_suavizado<span class="op">=</span><span class="dv">0</span>).fit(dataset)</span>
<span id="cb32-158"><a href="#cb32-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-159"><a href="#cb32-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-160"><a href="#cb32-160" aria-hidden="true" tabindex="-1"></a>Los parametros se encuentran en las atributos <span class="in">`modelo.frase`</span> y <span class="in">`modelo.hist`</span>, en el caso de <span class="in">`modelo.hist`</span> este tiene un valor de <span class="in">`{python} Markdown(f'{modelo.hist}')`</span>. Se observa que <span class="in">`modelo.frase`</span> es un diccionario donde el índice es el identificador del segmento y el valor corresponde a la frecuencia. Por otro lado, el método <span class="in">`modelo._log_prob`</span> (ver @lst-modelo-n-gram) utiliza la información de <span class="in">`modelo.frase`</span> y <span class="in">`modelo.hist`</span> para calcular el logaritmo de la probabilidad. En las siguientes instrucciones se representa la información de <span class="in">`modelo.frase`</span> y <span class="in">`modelo.hist`</span> en un vector. Lo primero es guarda en la variable <span class="in">`den`</span> el logaritmo de <span class="in">`modelo.hist`</span>, después se utiliza la variable <span class="in">`idx`</span> para dar un orden al vocabulario, es decir, el primer elemento de <span class="in">`idx`</span> corresponderá a la primera palabra del vocabulario y así sucesivamente. Utilizando <span class="in">`idx`</span> se itera por todo el vocabulario y se guarda el logaritmo de la probabilidad para cada segmento en el arreglo <span class="in">`pesos`</span>.  </span>
<span id="cb32-161"><a href="#cb32-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-164"><a href="#cb32-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-165"><a href="#cb32-165" aria-hidden="true" tabindex="-1"></a>den <span class="op">=</span> np.log(modelo.hist)</span>
<span id="cb32-166"><a href="#cb32-166" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> <span class="bu">sorted</span>(modelo.frase.keys())</span>
<span id="cb32-167"><a href="#cb32-167" aria-hidden="true" tabindex="-1"></a>pesos <span class="op">=</span> np.array(</span>
<span id="cb32-168"><a href="#cb32-168" aria-hidden="true" tabindex="-1"></a>    [np.log(modelo.frase[k]) <span class="op">-</span> den</span>
<span id="cb32-169"><a href="#cb32-169" aria-hidden="true" tabindex="-1"></a>     <span class="cf">for</span> k <span class="kw">in</span> idx]</span>
<span id="cb32-170"><a href="#cb32-170" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-171"><a href="#cb32-171" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-172"><a href="#cb32-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-173"><a href="#cb32-173" aria-hidden="true" tabindex="-1"></a>La variable <span class="in">`pesos`</span> tiene un tamaño de <span class="in">`{python} Markdown(f'{pesos.shape[0]}')`</span> que corresponde al tamaño del vocabulario. Para concluir el ejemplo, se va a calcular el logaritmo de observar la frase *Buenos días*. Lo primero que se tiene que realizar es conocer la posición de cada segmento (e.g., palabra) en el vector <span class="in">`pesos`</span> esto se realiza con la asociación mostrada en <span class="in">`idx2pos`</span>. Lo segundo es crear un vector de ceros (i.e., <span class="in">`vec`</span>) que contendrá la frase segmentadas. El tercer paso es segmentar la frase, iterar por cada segmento y agregar uno en la posición que corresponde a cada segmento en <span class="in">`vec`</span>. El resultado es que <span class="in">`vec`</span> tiene codificada la frase tal y como la realiza <span class="in">`ModeloNGram.`</span></span>
<span id="cb32-174"><a href="#cb32-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-177"><a href="#cb32-177" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-178"><a href="#cb32-178" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-179"><a href="#cb32-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-180"><a href="#cb32-180" aria-hidden="true" tabindex="-1"></a>idx2pos <span class="op">=</span> {k: v <span class="cf">for</span> v, k <span class="kw">in</span> <span class="bu">enumerate</span>(idx)}</span>
<span id="cb32-181"><a href="#cb32-181" aria-hidden="true" tabindex="-1"></a>vec <span class="op">=</span> np.zeros(<span class="bu">len</span>(pesos))</span>
<span id="cb32-182"><a href="#cb32-182" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> seg <span class="kw">in</span> modelo.segmentar(<span class="st">'Buenos días'</span>):</span>
<span id="cb32-183"><a href="#cb32-183" aria-hidden="true" tabindex="-1"></a>    vec[idx2pos[<span class="ss">f'</span><span class="sc">{</span>seg<span class="sc">}</span><span class="ss">'</span>]] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb32-184"><a href="#cb32-184" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-185"><a href="#cb32-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-186"><a href="#cb32-186" aria-hidden="true" tabindex="-1"></a>Con la información de <span class="in">`vec`</span> y <span class="in">`pesos`</span> se puede calcular el logaritmo de la probabilidad el cual corresponde al producto punto entre <span class="in">`vec`</span> y <span class="in">`pesos`</span> tal como se muestra en la siguiente instrucción. </span>
<span id="cb32-187"><a href="#cb32-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-190"><a href="#cb32-190" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-191"><a href="#cb32-191" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-192"><a href="#cb32-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-193"><a href="#cb32-193" aria-hidden="true" tabindex="-1"></a><span class="ss">f'</span><span class="sc">{</span>np<span class="sc">.</span>dot(vec, pesos)<span class="sc">:0.4f}</span><span class="ss">'</span></span>
<span id="cb32-194"><a href="#cb32-194" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-195"><a href="#cb32-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-196"><a href="#cb32-196" aria-hidden="true" tabindex="-1"></a>Se puede verificar que el valor de <span class="in">`modelo._log_prob("Buenos días")`</span> corresponde a <span class="in">`{python} Markdown(f'{modelo._log_prob("Buenos días"):0.4f}')`</span>, que es equivalente al encontrado por la representación alternativa. </span>
<span id="cb32-197"><a href="#cb32-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-198"><a href="#cb32-198" aria-hidden="true" tabindex="-1"></a>Se observa que la variable <span class="in">`vec`</span> y <span class="in">`pesos`</span> se pueden considerar como vectores que están $\mathbb R^d$ donde $d$ tiene un valor de <span class="in">`{python} Markdown(f'{pesos.shape[0]}')`</span>; por otro lado, la frase *Buenos días* está codificada en <span class="in">`vec`</span>, haciendo que esta este representada como un vector en $\mathbb R.$</span>
<span id="cb32-199"><a href="#cb32-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-200"><a href="#cb32-200" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bolsa de Palabras Dispersa </span></span>
<span id="cb32-201"><a href="#cb32-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-202"><a href="#cb32-202" aria-hidden="true" tabindex="-1"></a>La idea anterior se podría considerar como una bolsa de palabras, donde cada término o segmento de palabra $t$ está asociado a un vector único $\mathbf{v_t} \in \mathbb R^d$ donde la $i$-ésima componente, i.e., $\mathbf{v_t}_i$, es diferente de cero y $\forall_{j \neq i} \mathbf{v_t}_j=0$. Es decir la $i$-ésima componente está asociada al término $t$, se podría pensar que si el vocabulario está ordenado de alguna manera, entonces $t$ está en la posición $i$. Por otro lado el valor que contiene la componente se usa para representar alguna característica del término. </span>
<span id="cb32-203"><a href="#cb32-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-204"><a href="#cb32-204" aria-hidden="true" tabindex="-1"></a>El conjunto de vectores $\mathbf v$ corresponde al vocabulario, teniendo $d$ diferentes token en el mismo y por definición $\forall_{i \neq j} \mathbf{v_i} \cdot \mathbf{v_j} = 0$, donde $\mathbf{v_i} \in \mathbb R^d$, $\mathbf{v_j} \in \mathbb R^d$, y $(\cdot)$ es el producto punto. Cabe mencionar que cualquier segmento fuera del vocabulario es descartado. </span>
<span id="cb32-205"><a href="#cb32-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-206"><a href="#cb32-206" aria-hidden="true" tabindex="-1"></a>Usando esta notación, un texto $x$ está representado por una secuencia de términos, i.e., $(t_1, t_2, \ldots)$; la secuencia puede tener repeticiones es decir, $t_j = t_k$. Utilizando la característica de que cada término está asociado a un vector $\mathbf v$, se transforma la secuencia de términos a una secuencia de vectores (manteniendo las repeticiones), i.e., $(\mathbf{v_{t_1}}, \mathbf{v_{t_2}}, \ldots)$. Finalmente, el texto $x$ se representa como:</span>
<span id="cb32-207"><a href="#cb32-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-208"><a href="#cb32-208" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-209"><a href="#cb32-209" aria-hidden="true" tabindex="-1"></a>\mathbf x = \frac{\sum_t \mathbf{v_t}}{\lVert \sum_t \mathbf{v_t} \rVert},</span>
<span id="cb32-210"><a href="#cb32-210" aria-hidden="true" tabindex="-1"></a>$$ {#eq-bolsa-palabras}</span>
<span id="cb32-211"><a href="#cb32-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-212"><a href="#cb32-212" aria-hidden="true" tabindex="-1"></a>donde la suma se hace para todos los elementos de la secuencia, $\mathbf x \in \mathbb R^d$, y $\lVert \mathbf w \rVert$ es la norma Euclideana del vector $\mathbf w.$</span>
<span id="cb32-213"><a href="#cb32-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-216"><a href="#cb32-216" aria-hidden="true" tabindex="-1"></a><span class="in">```{dot}</span></span>
<span id="cb32-217"><a href="#cb32-217" aria-hidden="true" tabindex="-1"></a><span class="co">//| echo: false</span></span>
<span id="cb32-218"><a href="#cb32-218" aria-hidden="true" tabindex="-1"></a><span class="co">//| fig-cap: Diagrama Bolsa de Palabras Dispersa</span></span>
<span id="cb32-219"><a href="#cb32-219" aria-hidden="true" tabindex="-1"></a><span class="co">//| label: fig-repr-texto-bolsa-dispersa</span></span>
<span id="cb32-220"><a href="#cb32-220" aria-hidden="true" tabindex="-1"></a><span class="co">//| file: fig/repr-bolsa-dispersa.dot</span></span>
<span id="cb32-221"><a href="#cb32-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-222"><a href="#cb32-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-223"><a href="#cb32-223" aria-hidden="true" tabindex="-1"></a>Antes de iniciar la descripción detallada del proceso de representación utilizando una bolsa de palabras dispersas, es conveniente ilustrar este proceso mediante la @fig-repr-texto-bolsa-dispersa. El **texto segmentado** es el resultado del proceso ilustrado en @fig-pre-procesamiento. El texto segmentado puede seguir dos caminos, en la parte superior se encuentra el caso cuando los pesos han sido identificados previamente y en la parte inferior es el procedimiento cuando los pesos se estiman mediante un corpus específico que normalmente es un conjunto de entrenamiento. </span>
<span id="cb32-224"><a href="#cb32-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-225"><a href="#cb32-225" aria-hidden="true" tabindex="-1"></a><span class="fu">### Pesado de Términos </span></span>
<span id="cb32-226"><a href="#cb32-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-227"><a href="#cb32-227" aria-hidden="true" tabindex="-1"></a>Como se había mencionado el valor que tiene la componente $i$-ésima del vector $\mathbf{v_t}_i$ corresponde a una característica del término asociado, este procedimiento se le conoce como el **esquema de pesado**. Por ejemplo, si el valor es $1$ (i.e., $\mathbf{v_{t_i}} = 1$) entonces el valor está indicando solo la presencia del término, este es el caso más simple. Considerando la @eq-bolsa-palabras se observa que el resultado, $\mathbf x$, cuenta las repeticiones de cada término, por esta característica a este esquema se le conoce como **frecuencia de términos** (*term frequency (TF)*). </span>
<span id="cb32-228"><a href="#cb32-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-229"><a href="#cb32-229" aria-hidden="true" tabindex="-1"></a>Una medida que complementa la información que tiene la frecuencia de términos es el inverso de la frecuencia del término (*Inverse Document Frequency (IDF)*) en la colección, esta medida propuesta por @Jones1972 se usa en un método de pesado descrito por @Salton1973 el cual es conocido como **TFIDF**. Este método de pesado propone el considerar el producto de la frecuencia del término y el inverso de la frecuencia del término (*Inverse Document Frequency (IDF)* ) en la colección como el peso del término.</span>
<span id="cb32-230"><a href="#cb32-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-231"><a href="#cb32-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-232"><a href="#cb32-232" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ejemplos {#sec-bolsa-dispersa-ejemplos}</span></span>
<span id="cb32-233"><a href="#cb32-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-236"><a href="#cb32-236" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-237"><a href="#cb32-237" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-238"><a href="#cb32-238" aria-hidden="true" tabindex="-1"></a>bow <span class="op">=</span> BoW(lang<span class="op">=</span><span class="st">'es'</span>)</span>
<span id="cb32-239"><a href="#cb32-239" aria-hidden="true" tabindex="-1"></a>tm <span class="op">=</span> bow.bow</span>
<span id="cb32-240"><a href="#cb32-240" aria-hidden="true" tabindex="-1"></a>vec <span class="op">=</span> tm[<span class="st">'Buen día'</span>]</span>
<span id="cb32-241"><a href="#cb32-241" aria-hidden="true" tabindex="-1"></a>key_f <span class="op">=</span> Markdown(<span class="ss">f'$</span><span class="sc">{</span>vec[<span class="dv">0</span>][<span class="dv">0</span>]<span class="sc">}</span><span class="ss">$'</span>)</span>
<span id="cb32-242"><a href="#cb32-242" aria-hidden="true" tabindex="-1"></a>key_txt <span class="op">=</span> Markdown(<span class="ss">f'*</span><span class="sc">{</span>tm<span class="sc">.</span>id2token[vec[<span class="dv">0</span>][<span class="dv">0</span>]]<span class="sc">}</span><span class="ss">*'</span>)</span>
<span id="cb32-243"><a href="#cb32-243" aria-hidden="true" tabindex="-1"></a>idf_f <span class="op">=</span> Markdown(<span class="ss">f'$</span><span class="sc">{</span>vec[<span class="dv">0</span>][<span class="dv">1</span>]<span class="sc">:0.4f}</span><span class="ss">$'</span>)</span>
<span id="cb32-244"><a href="#cb32-244" aria-hidden="true" tabindex="-1"></a>len_f <span class="op">=</span> Markdown(<span class="ss">f'$</span><span class="sc">{</span><span class="bu">len</span>(vec)<span class="sc">}</span><span class="ss">$'</span>)</span>
<span id="cb32-245"><a href="#cb32-245" aria-hidden="true" tabindex="-1"></a>voc_f <span class="op">=</span> Markdown(<span class="ss">f'$</span><span class="sc">{</span><span class="bu">len</span>(bow.names)<span class="sc">}</span><span class="ss">$'</span>)</span>
<span id="cb32-246"><a href="#cb32-246" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-247"><a href="#cb32-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-248"><a href="#cb32-248" aria-hidden="true" tabindex="-1"></a>En los siguientes ejemplos se usa una bolsa de palabras con un pesado TFIDF pre-entrenada, los datos de esta bolsa de palabras se encuentra en el atributo <span class="in">`BoW.bow`</span>. El tamaño del vocabulario es <span class="in">`{python} voc_f`</span>, que está compuesto por palabras, gramas de palabras y caracteres. En el siguiente ejemplo se muestran los primeros tres gramas con sus respectivos valores TFIDF de la frase *Buen día*. Se puede observar que el <span class="in">`tm`</span> regresa una lista de pares, donde la primera parte es el identificador del término, e.g., <span class="in">`{python} key_f`</span> y el segundo es el valor TFIDF, e.g., <span class="in">`{python} idf_f`</span>. La lista tiene un tamaño de <span class="in">`{python} len_f`</span> elementos, el resto de los  <span class="in">`{python} voc_f`</span> componentes son cero dado que no se encuentran en el texto representado. </span>
<span id="cb32-249"><a href="#cb32-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-252"><a href="#cb32-252" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-253"><a href="#cb32-253" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-254"><a href="#cb32-254" aria-hidden="true" tabindex="-1"></a>bow <span class="op">=</span> BoW(lang<span class="op">=</span><span class="st">'es'</span>)</span>
<span id="cb32-255"><a href="#cb32-255" aria-hidden="true" tabindex="-1"></a>tm <span class="op">=</span> bow.bow</span>
<span id="cb32-256"><a href="#cb32-256" aria-hidden="true" tabindex="-1"></a>vec <span class="op">=</span> tm[<span class="st">'Buen día'</span>]</span>
<span id="cb32-257"><a href="#cb32-257" aria-hidden="true" tabindex="-1"></a>vec[:<span class="dv">3</span>]</span>
<span id="cb32-258"><a href="#cb32-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-259"><a href="#cb32-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-260"><a href="#cb32-260" aria-hidden="true" tabindex="-1"></a>El uso del identificador del término se puede reemplazar por el término para poder visualizar mejor la representación del texto en el espacio vectorial. El diccionario que se encuentra en <span class="in">`BoW.names`</span> hace la relación identificador a término. Se puede ver que el primer elemento del vector es el bigrama *buen~dia*, seguido por *buen* y el tercer término es *dia*. Los siguientes términos que no se muestran corresponden a gramas de caracteres. El valor TFIDF no indica la importancia del término, mientras mayor sea el valor, se considera más importante de acuerdo al TFIDF. En este ejemplo el bigrama tiene más importancia que las palabras y la palabra *buen* es más significativa que *dia*.</span>
<span id="cb32-261"><a href="#cb32-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-264"><a href="#cb32-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-265"><a href="#cb32-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-266"><a href="#cb32-266" aria-hidden="true" tabindex="-1"></a>[(bow.names[k], v)</span>
<span id="cb32-267"><a href="#cb32-267" aria-hidden="true" tabindex="-1"></a> <span class="cf">for</span> k, v <span class="kw">in</span> vec[:<span class="dv">3</span>]]</span>
<span id="cb32-268"><a href="#cb32-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-269"><a href="#cb32-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-270"><a href="#cb32-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-273"><a href="#cb32-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-274"><a href="#cb32-274" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb32-275"><a href="#cb32-275" aria-hidden="true" tabindex="-1"></a>txt <span class="op">=</span> <span class="st">'Buen día colegas'</span></span>
<span id="cb32-276"><a href="#cb32-276" aria-hidden="true" tabindex="-1"></a>vec2 <span class="op">=</span> tm[txt]</span>
<span id="cb32-277"><a href="#cb32-277" aria-hidden="true" tabindex="-1"></a>idf2_f <span class="op">=</span> Markdown(<span class="ss">f'$</span><span class="sc">{</span>vec2[<span class="dv">0</span>][<span class="dv">1</span>]<span class="sc">:0.4f}</span><span class="ss">$'</span>)</span>
<span id="cb32-278"><a href="#cb32-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-279"><a href="#cb32-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-280"><a href="#cb32-280" aria-hidden="true" tabindex="-1"></a>Con el objetivo de ilustrar una heurística que ha dado buenos resultados en el siguiente ejemplo se presentan las primeras cuatro componentes del texto *Buen día colegas*. Se puede observar como los valores de IDF de los términos comunes cambiaron, por ejemplo para el caso de `{python} key_txt` cambio de `{python} idf_f` a `{python} idf2_f`. Este es el resultado de que los valores están normalizados tal como se muestra en la @eq-bolsa-palabras. Por otro lado, se observa que ahora el término más significativo es la palabra *colegas*. </span>
<span id="cb32-281"><a href="#cb32-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-284"><a href="#cb32-284" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-285"><a href="#cb32-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-286"><a href="#cb32-286" aria-hidden="true" tabindex="-1"></a>txt <span class="op">=</span> <span class="st">'Buen día colegas'</span></span>
<span id="cb32-287"><a href="#cb32-287" aria-hidden="true" tabindex="-1"></a>[(tm.id2token[k], v)</span>
<span id="cb32-288"><a href="#cb32-288" aria-hidden="true" tabindex="-1"></a> <span class="cf">for</span> k, v <span class="kw">in</span> tm[txt][:<span class="dv">4</span>]]</span>
<span id="cb32-289"><a href="#cb32-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-290"><a href="#cb32-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-291"><a href="#cb32-291" aria-hidden="true" tabindex="-1"></a>Una manera de visualizar la representación es creando una nube de palabras de los términos, donde el tamaño del termino corresponde al valor TFIDF. En la @fig-repr-texto-nube muestra la nube de palabras generada con los términos y sus respectivos valores IDF del texto *Es un placer estar platicando con ustedes.*</span>
<span id="cb32-292"><a href="#cb32-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-295"><a href="#cb32-295" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-296"><a href="#cb32-296" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb32-297"><a href="#cb32-297" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: Nube de términos</span></span>
<span id="cb32-298"><a href="#cb32-298" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-repr-texto-nube</span></span>
<span id="cb32-299"><a href="#cb32-299" aria-hidden="true" tabindex="-1"></a>txt <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb32-300"><a href="#cb32-300" aria-hidden="true" tabindex="-1"></a>tokens <span class="op">=</span> {tm.id2token[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> tm[txt]}</span>
<span id="cb32-301"><a href="#cb32-301" aria-hidden="true" tabindex="-1"></a>word_cloud <span class="op">=</span> WordCloud().generate_from_frequencies(tokens)</span>
<span id="cb32-302"><a href="#cb32-302" aria-hidden="true" tabindex="-1"></a>plt.imshow(word_cloud, interpolation<span class="op">=</span><span class="st">'bilinear'</span>)</span>
<span id="cb32-303"><a href="#cb32-303" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">False</span>)</span>
<span id="cb32-304"><a href="#cb32-304" aria-hidden="true" tabindex="-1"></a>plt.tick_params(left<span class="op">=</span><span class="va">False</span>, right<span class="op">=</span><span class="va">False</span>, labelleft<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb32-305"><a href="#cb32-305" aria-hidden="true" tabindex="-1"></a>                labelbottom<span class="op">=</span><span class="va">False</span>, bottom<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb32-306"><a href="#cb32-306" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-307"><a href="#cb32-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-308"><a href="#cb32-308" aria-hidden="true" tabindex="-1"></a>El texto se representa en un espacio vectorial, entonces es posible comparar la similitud entre dos textos en esta representación, por ejemplo, en el siguiente ejemplo se compara la similitud coseno entre los textos *Es un placer estar platicando con ustedes.* y *La lluvia genera un caos en la ciudad.* El valor obtenido es cercano a cero indicando que estos textos no son similares. </span>
<span id="cb32-309"><a href="#cb32-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-312"><a href="#cb32-312" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-313"><a href="#cb32-313" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-314"><a href="#cb32-314" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb32-315"><a href="#cb32-315" aria-hidden="true" tabindex="-1"></a>txt2 <span class="op">=</span> <span class="st">'La lluvia genera un caos en la ciudad.'</span></span>
<span id="cb32-316"><a href="#cb32-316" aria-hidden="true" tabindex="-1"></a>vec1 <span class="op">=</span> tm[txt1]</span>
<span id="cb32-317"><a href="#cb32-317" aria-hidden="true" tabindex="-1"></a>vec2 <span class="op">=</span> tm[txt2]</span>
<span id="cb32-318"><a href="#cb32-318" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> {k: v <span class="cf">for</span> k, v <span class="kw">in</span> vec1}</span>
<span id="cb32-319"><a href="#cb32-319" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>([f[k] <span class="op">*</span> v <span class="cf">for</span> k, v <span class="kw">in</span> vec2 <span class="cf">if</span> k <span class="kw">in</span> f])</span>
<span id="cb32-320"><a href="#cb32-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-321"><a href="#cb32-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-322"><a href="#cb32-322" aria-hidden="true" tabindex="-1"></a>Complementando el ejemplo anterior, en esta ocasión se comparan dos textos que comparten el concepto *plática*, estos son *Es un placer estar platicando con ustedes.* y *Estoy dando una platica en Morelia.* se puede observar que estos textos son más similares que los ejemplos anteriores. </span>
<span id="cb32-323"><a href="#cb32-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-326"><a href="#cb32-326" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-327"><a href="#cb32-327" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-328"><a href="#cb32-328" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb32-329"><a href="#cb32-329" aria-hidden="true" tabindex="-1"></a>txt2 <span class="op">=</span> <span class="st">'Estoy dando una platica en Morelia.'</span></span>
<span id="cb32-330"><a href="#cb32-330" aria-hidden="true" tabindex="-1"></a>vec1 <span class="op">=</span> tm[txt1]</span>
<span id="cb32-331"><a href="#cb32-331" aria-hidden="true" tabindex="-1"></a>vec2 <span class="op">=</span> tm[txt2]</span>
<span id="cb32-332"><a href="#cb32-332" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> {k: v <span class="cf">for</span> k, v <span class="kw">in</span> vec1}</span>
<span id="cb32-333"><a href="#cb32-333" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>([f[k] <span class="op">*</span> v <span class="cf">for</span> k, v <span class="kw">in</span> vec2 <span class="cf">if</span> k <span class="kw">in</span> f])</span>
<span id="cb32-334"><a href="#cb32-334" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-335"><a href="#cb32-335" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb32-336"><a href="#cb32-336" aria-hidden="true" tabindex="-1"></a> Habiendo realizado la similitud entre algunos textos lleva a preguntarse cómo será la distribución de similitud entre varios textos, para poder contestar esta pregunta, se utilizarán los datos de <span class="co">[</span><span class="ot">Delitos</span><span class="co">](https://ingeotec.github.io/Delitos)</span>, los cuales se guardan en la variable <span class="in">`D`</span> tal y como se en las siguientes instrucciones. </span>
<span id="cb32-337"><a href="#cb32-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-340"><a href="#cb32-340" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-341"><a href="#cb32-341" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-342"><a href="#cb32-342" aria-hidden="true" tabindex="-1"></a>fname <span class="op">=</span> <span class="st">'delitos/delitos_ingeotec_Es_train.json'</span></span>
<span id="cb32-343"><a href="#cb32-343" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> <span class="bu">list</span>(tweet_iterator(fname))</span>
<span id="cb32-344"><a href="#cb32-344" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-345"><a href="#cb32-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-346"><a href="#cb32-346" aria-hidden="true" tabindex="-1"></a>El primer paso es representar todos los textos en el espacio vectorial de la bolsa de palabras, lo cual se logra con el método <span class="in">`BoW.transform`</span> (primera linea), el segundo paso es calcular la similitud entre todos los textos, como se muestra en la segunda linea. </span>
<span id="cb32-347"><a href="#cb32-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-350"><a href="#cb32-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-351"><a href="#cb32-351" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-352"><a href="#cb32-352" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> tm.transform(D)</span>
<span id="cb32-353"><a href="#cb32-353" aria-hidden="true" tabindex="-1"></a>sim <span class="op">=</span> np.dot(X, X.T)</span>
<span id="cb32-354"><a href="#cb32-354" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-355"><a href="#cb32-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-356"><a href="#cb32-356" aria-hidden="true" tabindex="-1"></a>La distribución de similitud se muestra en la @fig-text-repr-similitud-bow se puede observar que las similitudes se encuentran concentradas cerca del cero, esto indica que la mayoría de los textos están distantes, esto es el resultado de la bolsa de palabras discreta que se enfoca en modelar las palabras y no el significado de las mismas. </span>
<span id="cb32-357"><a href="#cb32-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-358"><a href="#cb32-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-361"><a href="#cb32-361" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-362"><a href="#cb32-362" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb32-363"><a href="#cb32-363" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: Histograma de la similitud</span></span>
<span id="cb32-364"><a href="#cb32-364" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-text-repr-similitud-bow</span></span>
<span id="cb32-365"><a href="#cb32-365" aria-hidden="true" tabindex="-1"></a>sns.displot(sim.data)</span>
<span id="cb32-366"><a href="#cb32-366" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-367"><a href="#cb32-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-368"><a href="#cb32-368" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bolsa de Palabras Densa </span></span>
<span id="cb32-369"><a href="#cb32-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-370"><a href="#cb32-370" aria-hidden="true" tabindex="-1"></a>La @fig-repr-texto-bolsa-densa muestra el procedimiento que se sigue para representar un texto en una bolsa de palabras dispersa. En primer lugar la bolsa de palabras densa considera que los vectores asociados a los términos se encuentra pre-entrenados y en general no es factible entrenarlos en el momento, esto por el tiempo que lleva estimar estos vectores. </span>
<span id="cb32-371"><a href="#cb32-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-374"><a href="#cb32-374" aria-hidden="true" tabindex="-1"></a><span class="in">```{dot}</span></span>
<span id="cb32-375"><a href="#cb32-375" aria-hidden="true" tabindex="-1"></a><span class="co">//| echo: false</span></span>
<span id="cb32-376"><a href="#cb32-376" aria-hidden="true" tabindex="-1"></a><span class="co">//| fig-cap: Diagrama Bolsa de Palabras Densa</span></span>
<span id="cb32-377"><a href="#cb32-377" aria-hidden="true" tabindex="-1"></a><span class="co">//| label: fig-repr-texto-bolsa-densa</span></span>
<span id="cb32-378"><a href="#cb32-378" aria-hidden="true" tabindex="-1"></a><span class="co">//| file: fig/repr-bolsa-densa.dot</span></span>
<span id="cb32-379"><a href="#cb32-379" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-380"><a href="#cb32-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-381"><a href="#cb32-381" aria-hidden="true" tabindex="-1"></a>El texto se representa como el vector $\mathbf u$ que se calcula usando la @eq-bolsa-densas donde se observa que es la suma de los vectores asociados a cada término más un coeficiente $\mathbf{w_0}$. En particular el coeficiente $\mathbf{w_0} \in \mathbb R^{M}$ no se encuentra en todas las representaciones densas, pero en la representación que se usará contiene este vector, $M$ es la dimensión de la representación densa. </span>
<span id="cb32-382"><a href="#cb32-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-383"><a href="#cb32-383" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-384"><a href="#cb32-384" aria-hidden="true" tabindex="-1"></a>\mathbf u = \sum_t \mathbf{u_t} + \mathbf{w_0}.</span>
<span id="cb32-385"><a href="#cb32-385" aria-hidden="true" tabindex="-1"></a>$$ {#eq-bolsa-densas}</span>
<span id="cb32-386"><a href="#cb32-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-387"><a href="#cb32-387" aria-hidden="true" tabindex="-1"></a>En vector $\mathbf {u_t}$ está asociado al término $t$, en particular este vector en la representación densa que se describirá está definido en términos de una bolsa de palabras dispersa (@eq-bolsa-palabras) como se puede observar en la @eq-bolsa-densa-ut</span>
<span id="cb32-388"><a href="#cb32-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-389"><a href="#cb32-389" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-390"><a href="#cb32-390" aria-hidden="true" tabindex="-1"></a>\mathbf{u_t} = \frac{\mathbf W \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert},</span>
<span id="cb32-391"><a href="#cb32-391" aria-hidden="true" tabindex="-1"></a>$$ {#eq-bolsa-densa-ut}</span>
<span id="cb32-392"><a href="#cb32-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-393"><a href="#cb32-393" aria-hidden="true" tabindex="-1"></a>donde $\mathbf W \in \mathbb R^{M \times d}$ es la matriz que hace la proyección de la representación dispersa a la representación densa, se puede observar esa operación está normalizada con la norma Euclideana de la representación dispersa. </span>
<span id="cb32-394"><a href="#cb32-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-395"><a href="#cb32-395" aria-hidden="true" tabindex="-1"></a>Combinando las @eq-bolsa-densas y @eq-bolsa-densa-ut queda la </span>
<span id="cb32-396"><a href="#cb32-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-397"><a href="#cb32-397" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-398"><a href="#cb32-398" aria-hidden="true" tabindex="-1"></a>\begin{split}</span>
<span id="cb32-399"><a href="#cb32-399" aria-hidden="true" tabindex="-1"></a>\mathbf{u_t} &amp;= \sum_t \frac{\mathbf W \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert} + \mathbf{w_0} <span class="sc">\\</span></span>
<span id="cb32-400"><a href="#cb32-400" aria-hidden="true" tabindex="-1"></a>&amp;= \mathbf W \frac{\sum_t \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert} + \mathbf{w_0},</span>
<span id="cb32-401"><a href="#cb32-401" aria-hidden="true" tabindex="-1"></a>\end{split}</span>
<span id="cb32-402"><a href="#cb32-402" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-403"><a href="#cb32-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-404"><a href="#cb32-404" aria-hidden="true" tabindex="-1"></a>donde se puede observar la representación dispersa (@eq-bolsa-palabras), i.e., $\frac{\sum_t \mathbf {v_t}}{\lVert \sum_t \mathbf{v_t} \rVert}$ lo cual resulta en la @eq-bolsa-densa-texto</span>
<span id="cb32-405"><a href="#cb32-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-406"><a href="#cb32-406" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb32-407"><a href="#cb32-407" aria-hidden="true" tabindex="-1"></a>\mathbf u = \mathbf W \mathbf x + \mathbf{w_0},</span>
<span id="cb32-408"><a href="#cb32-408" aria-hidden="true" tabindex="-1"></a>$$ {#eq-bolsa-densa-texto}</span>
<span id="cb32-409"><a href="#cb32-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-410"><a href="#cb32-410" aria-hidden="true" tabindex="-1"></a>que representa un texto en el vector $\mathbf u \in \mathbb R^M.$</span>
<span id="cb32-411"><a href="#cb32-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-412"><a href="#cb32-412" aria-hidden="true" tabindex="-1"></a>Para algunas representaciones densas, las componentes de la matriz de transformación $\mathcal W$ están asociadas a conceptos, en el caso que se analiza estas están asociadas a palabras claves o emojis. </span>
<span id="cb32-413"><a href="#cb32-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-414"><a href="#cb32-414" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ejemplos </span></span>
<span id="cb32-415"><a href="#cb32-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-416"><a href="#cb32-416" aria-hidden="true" tabindex="-1"></a>Continuando con los ejemplos presentados para la bolsa dispersa (@sec-bolsa-dispersa-ejemplos) en esta sección se hace el análisis con la representación de palabras densa. El primer paso es inicializar la clase que contiene las representaciones densas, esto se hace con la siguiente instrucción. </span>
<span id="cb32-417"><a href="#cb32-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-420"><a href="#cb32-420" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-421"><a href="#cb32-421" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-422"><a href="#cb32-422" aria-hidden="true" tabindex="-1"></a>dense <span class="op">=</span> DenseBoW(lang<span class="op">=</span><span class="st">'es'</span>,</span>
<span id="cb32-423"><a href="#cb32-423" aria-hidden="true" tabindex="-1"></a>                 voc_size_exponent<span class="op">=</span><span class="dv">15</span>,</span>
<span id="cb32-424"><a href="#cb32-424" aria-hidden="true" tabindex="-1"></a>                 emoji<span class="op">=</span><span class="va">False</span>, keyword<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb32-425"><a href="#cb32-425" aria-hidden="true" tabindex="-1"></a>                 distance_hyperplane<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb32-426"><a href="#cb32-426" aria-hidden="true" tabindex="-1"></a>                 dataset<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb32-427"><a href="#cb32-427" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-428"><a href="#cb32-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-429"><a href="#cb32-429" aria-hidden="true" tabindex="-1"></a>Para representar un texto en el espacio vectorial denso se utiliza el método <span class="in">`transform`</span>, por ejemplo la siguiente instrucción representa el texto *Es un placer estar platicando con ustedes.* Solo se visualizan los valores de las primeras tres componentes.</span>
<span id="cb32-430"><a href="#cb32-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-433"><a href="#cb32-433" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-434"><a href="#cb32-434" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-435"><a href="#cb32-435" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb32-436"><a href="#cb32-436" aria-hidden="true" tabindex="-1"></a>dense.transform([txt1])[<span class="dv">0</span>, :<span class="dv">3</span>]</span>
<span id="cb32-437"><a href="#cb32-437" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-438"><a href="#cb32-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-439"><a href="#cb32-439" aria-hidden="true" tabindex="-1"></a>Lo primero que se observa es que los valores son negativos, a diferencia del caso disperso donde todos los valores son positivos. En este tipo de representación cada componente está asociada a una palabra las cuales se pueden conocer en el atributo <span class="in">`names`</span>. El siguiente código muestra las tres primeras palabras asociadas al ejemplo anterior. </span>
<span id="cb32-440"><a href="#cb32-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-443"><a href="#cb32-443" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-444"><a href="#cb32-444" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-445"><a href="#cb32-445" aria-hidden="true" tabindex="-1"></a>dense.names[:<span class="dv">3</span>]</span>
<span id="cb32-446"><a href="#cb32-446" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-447"><a href="#cb32-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-448"><a href="#cb32-448" aria-hidden="true" tabindex="-1"></a>Siguiente la idea de utilizar una nube de palabras para visualizar el vector que representa el texto modelado, La @fig-repr-texto-nube-densa muestra las nubes de palabras generada con las características y sus respectivos valores del texto *Es un placer estar platicando con ustedes.* Durante la generación de la nube de palabras se decidió representar genera una nube de palabras con las palabras con coeficiente negativo más significativo y aquellas con los coeficientes positivos más significativos. Se puede observar que las palabras positivas contienen componentes que están relacionados al enunciado, pero al mismo tiempo leyendo los términos positivos es complicado construir el texto representado. Adicionalmente las términos negativos que se observan en la nube de palabras en su mayoría son hashtags que tiene muy poca relación al texto representado. </span>
<span id="cb32-449"><a href="#cb32-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-452"><a href="#cb32-452" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-453"><a href="#cb32-453" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb32-454"><a href="#cb32-454" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: Nube de características para el texto *Es un placer estar platicando con ustedes.*</span></span>
<span id="cb32-455"><a href="#cb32-455" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-repr-texto-nube-densa</span></span>
<span id="cb32-456"><a href="#cb32-456" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> dense.transform([txt1])</span>
<span id="cb32-457"><a href="#cb32-457" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> dense.names</span>
<span id="cb32-458"><a href="#cb32-458" aria-hidden="true" tabindex="-1"></a>tokens_pos <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">0</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb32-459"><a href="#cb32-459" aria-hidden="true" tabindex="-1"></a>tokens_neg <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="op">*</span> <span class="op">-</span><span class="dv">1</span> <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">0</span>]) <span class="cf">if</span> v <span class="op">&lt;</span> <span class="dv">0</span>}</span>
<span id="cb32-460"><a href="#cb32-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-461"><a href="#cb32-461" aria-hidden="true" tabindex="-1"></a>word_pos <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_pos)</span>
<span id="cb32-462"><a href="#cb32-462" aria-hidden="true" tabindex="-1"></a>word_neg <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_neg)</span>
<span id="cb32-463"><a href="#cb32-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-464"><a href="#cb32-464" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb32-465"><a href="#cb32-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-466"><a href="#cb32-466" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cloud, ax, title <span class="kw">in</span> <span class="bu">zip</span>([word_neg, word_pos],</span>
<span id="cb32-467"><a href="#cb32-467" aria-hidden="true" tabindex="-1"></a>                     [ax1, ax2],</span>
<span id="cb32-468"><a href="#cb32-468" aria-hidden="true" tabindex="-1"></a>                     [<span class="st">'Negativas'</span>, </span>
<span id="cb32-469"><a href="#cb32-469" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Positivas'</span>]):</span>
<span id="cb32-470"><a href="#cb32-470" aria-hidden="true" tabindex="-1"></a>    ax.imshow(cloud, interpolation<span class="op">=</span><span class="st">'bilinear'</span>)</span>
<span id="cb32-471"><a href="#cb32-471" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">False</span>)</span>
<span id="cb32-472"><a href="#cb32-472" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(left<span class="op">=</span><span class="va">False</span>, right<span class="op">=</span><span class="va">False</span>, labelleft<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb32-473"><a href="#cb32-473" aria-hidden="true" tabindex="-1"></a>                   labelbottom<span class="op">=</span><span class="va">False</span>, bottom<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb32-474"><a href="#cb32-474" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title)</span>
<span id="cb32-475"><a href="#cb32-475" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-476"><a href="#cb32-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-477"><a href="#cb32-477" aria-hidden="true" tabindex="-1"></a>Esta representación también permite comparación de similitud entre textos, en el siguiente ejemplo se calcula la similitud entre el texto *Es un placer estar platicando con ustedes.* y los textos *La lluvia genera un caos en la ciudad.* y *Estoy dando una platica en Morelia.* tal y como se hizo para la representación dispersa. Se puede observar que existe una mayor similitud entre los textos que contienen el concepto **plática**, lo cual es equivalente a lo que se observó en el ejemplo con bolsa de palabras discretas, pero los valores son significativamente mayores que en ese caso.</span>
<span id="cb32-478"><a href="#cb32-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-479"><a href="#cb32-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-482"><a href="#cb32-482" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-483"><a href="#cb32-483" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-484"><a href="#cb32-484" aria-hidden="true" tabindex="-1"></a>txt1 <span class="op">=</span> <span class="st">'Es un placer estar platicando con ustedes.'</span></span>
<span id="cb32-485"><a href="#cb32-485" aria-hidden="true" tabindex="-1"></a>txt2 <span class="op">=</span> <span class="st">'La lluvia genera un caos en la ciudad.'</span></span>
<span id="cb32-486"><a href="#cb32-486" aria-hidden="true" tabindex="-1"></a>txt3 <span class="op">=</span> <span class="st">'Estoy dando una platica en Morelia.'</span></span>
<span id="cb32-487"><a href="#cb32-487" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> dense.transform([txt1, txt2, txt3])</span>
<span id="cb32-488"><a href="#cb32-488" aria-hidden="true" tabindex="-1"></a>np.dot(X[<span class="dv">0</span>], X[<span class="dv">1</span>]), np.dot(X[<span class="dv">0</span>], X[<span class="dv">2</span>])</span>
<span id="cb32-489"><a href="#cb32-489" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-490"><a href="#cb32-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-491"><a href="#cb32-491" aria-hidden="true" tabindex="-1"></a>Los valores de similitud entre los enunciados anteriores, se puede visualizar en una nube de palabras, utilizando solo las características positivas. La @fig-repr-texto-nube-densa-comp muestra las nubes de palabras generadas, en ellas es complicado comprender la razón por la cual la frases que tiene el concepto *plática* están más cercanas, es probable que la cola de la distribución, es decir, las palabras menos significativas son las que acercan las dos oraciones. </span>
<span id="cb32-492"><a href="#cb32-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-495"><a href="#cb32-495" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-496"><a href="#cb32-496" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb32-497"><a href="#cb32-497" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: Nube de características positivas.</span></span>
<span id="cb32-498"><a href="#cb32-498" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-repr-texto-nube-densa-comp</span></span>
<span id="cb32-499"><a href="#cb32-499" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> dense.transform([txt1, txt2, txt3])</span>
<span id="cb32-500"><a href="#cb32-500" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> dense.names</span>
<span id="cb32-501"><a href="#cb32-501" aria-hidden="true" tabindex="-1"></a>tokens_pos <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">0</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb32-502"><a href="#cb32-502" aria-hidden="true" tabindex="-1"></a>tokens_neg <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">1</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb32-503"><a href="#cb32-503" aria-hidden="true" tabindex="-1"></a>tokens_otro <span class="op">=</span> {names[<span class="bu">id</span>]: v <span class="cf">for</span> <span class="bu">id</span>, v <span class="kw">in</span> <span class="bu">enumerate</span>(values[<span class="dv">2</span>]) <span class="cf">if</span> v <span class="op">&gt;</span> <span class="dv">0</span>}</span>
<span id="cb32-504"><a href="#cb32-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-505"><a href="#cb32-505" aria-hidden="true" tabindex="-1"></a>word_pos <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_pos)</span>
<span id="cb32-506"><a href="#cb32-506" aria-hidden="true" tabindex="-1"></a>word_neg <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_neg)</span>
<span id="cb32-507"><a href="#cb32-507" aria-hidden="true" tabindex="-1"></a>word_otro <span class="op">=</span> WordCloud().generate_from_frequencies(tokens_otro)</span>
<span id="cb32-508"><a href="#cb32-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-509"><a href="#cb32-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-510"><a href="#cb32-510" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2, ax3) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>)</span>
<span id="cb32-511"><a href="#cb32-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-512"><a href="#cb32-512" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cloud, ax, title <span class="kw">in</span> <span class="bu">zip</span>([word_pos, word_neg, word_otro],</span>
<span id="cb32-513"><a href="#cb32-513" aria-hidden="true" tabindex="-1"></a>                     [ax1, ax2, ax3],</span>
<span id="cb32-514"><a href="#cb32-514" aria-hidden="true" tabindex="-1"></a>                     [<span class="st">'Es un ... ustedes.'</span>, </span>
<span id="cb32-515"><a href="#cb32-515" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'La lluvia ... ciudad.'</span>,</span>
<span id="cb32-516"><a href="#cb32-516" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Estoy ... Morelia.'</span>]):</span>
<span id="cb32-517"><a href="#cb32-517" aria-hidden="true" tabindex="-1"></a>    ax.imshow(cloud, interpolation<span class="op">=</span><span class="st">'bilinear'</span>)</span>
<span id="cb32-518"><a href="#cb32-518" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">False</span>)</span>
<span id="cb32-519"><a href="#cb32-519" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(left<span class="op">=</span><span class="va">False</span>, right<span class="op">=</span><span class="va">False</span>, labelleft<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb32-520"><a href="#cb32-520" aria-hidden="true" tabindex="-1"></a>                   labelbottom<span class="op">=</span><span class="va">False</span>, bottom<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb32-521"><a href="#cb32-521" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title)</span>
<span id="cb32-522"><a href="#cb32-522" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-523"><a href="#cb32-523" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-524"><a href="#cb32-524" aria-hidden="true" tabindex="-1"></a>Al igual que en el caso disperso se puede calcular la distribución de similitud. Las siguientes instrucciones calcula la similitud coseno entre todos los ejemplos del conjunto de entrenamiento ($\mathcal T$). </span>
<span id="cb32-525"><a href="#cb32-525" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-528"><a href="#cb32-528" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-529"><a href="#cb32-529" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb32-530"><a href="#cb32-530" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> dense.transform(D)</span>
<span id="cb32-531"><a href="#cb32-531" aria-hidden="true" tabindex="-1"></a>sim <span class="op">=</span> np.dot(X, X.T)</span>
<span id="cb32-532"><a href="#cb32-532" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-533"><a href="#cb32-533" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-534"><a href="#cb32-534" aria-hidden="true" tabindex="-1"></a>La @fig-text-repr-similitud-dense muestra el histograma de las similitudes calculada mediante la bolsa densa. Aquí se puede observar que la gran mayoría de los ejemplos tiene una similitud mayor y tiene una desviación estándar mayor que la vista en la @fig-text-repr-similitud-bow. </span>
<span id="cb32-535"><a href="#cb32-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-538"><a href="#cb32-538" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb32-539"><a href="#cb32-539" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb32-540"><a href="#cb32-540" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: Histograma de la similitud usando bolsa de palabras densas</span></span>
<span id="cb32-541"><a href="#cb32-541" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-text-repr-similitud-dense</span></span>
<span id="cb32-542"><a href="#cb32-542" aria-hidden="true" tabindex="-1"></a>sns.displot(sim.flatten())</span>
<span id="cb32-543"><a href="#cb32-543" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-544"><a href="#cb32-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-545"><a href="#cb32-545" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-546"><a href="#cb32-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-547"><a href="#cb32-547" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-548"><a href="#cb32-548" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-549"><a href="#cb32-549" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-550"><a href="#cb32-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-551"><a href="#cb32-551" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-552"><a href="#cb32-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-553"><a href="#cb32-553" aria-hidden="true" tabindex="-1"></a></span>
</code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="http://creativecommons.org/licenses/by-sa/4.0/"><img src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" class="img-fluid"></a> <br> Esta obra está bajo una <a href="http://creativecommons.org/licenses/by-sa/4.0/">Licencia Creative Commons Atribución-CompartirIgual 4.0 Internacional</a></p>
</div>
  </div>
</footer>




</body></html>