on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}    
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          shell: bash -el {0}                
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
      - name: Install dependencies
        run: |
          conda install --yes numpy scipy scikit-learn nltk evomsa jupyter
          python -c "import nltk; nltk.download('stopwords')"
          which python
          cat ~/.bashrc
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}